UPDATE mangos_string SET content_loc4=null;

UPDATE mangos_string SET content_loc4='您应该选择角色或生物.' WHERE entry=1;
UPDATE mangos_string SET content_loc4='您应该选择一个生物.' WHERE entry=2;
UPDATE mangos_string SET content_loc4='|cffff0000[系统消息]: %s|r' WHERE entry=3;
UPDATE mangos_string SET content_loc4='|cffff0000[游戏广播]: %s|r' WHERE entry=4;
UPDATE mangos_string SET content_loc4='这里没有此命令的帮助信息' WHERE entry=5;
UPDATE mangos_string SET content_loc4='这个命令不存在' WHERE entry=6;
UPDATE mangos_string SET content_loc4='这里没有此类子命令' WHERE entry=7;
UPDATE mangos_string SET content_loc4='命令 %s 子命令是:%s' WHERE entry=8;
UPDATE mangos_string SET content_loc4='你可以使用的命令有:' WHERE entry=9;
UPDATE mangos_string SET content_loc4='命令语法格式错误.' WHERE entry=10;
UPDATE mangos_string SET content_loc4='你的账号级别是: %i' WHERE entry=11;
UPDATE mangos_string SET content_loc4='在线人数: %u (最多时: %u) 排队人数: %u (最多时: %u)' WHERE entry=12;
UPDATE mangos_string SET content_loc4='服务器正常运行时间: %s' WHERE entry=13;
UPDATE mangos_string SET content_loc4='玩家数据保存成功.' WHERE entry=14;
UPDATE mangos_string SET content_loc4='保存所有玩家数据成功.' WHERE entry=15;
UPDATE mangos_string SET content_loc4='在此服务器上有以下在线的G M:' WHERE entry=16;
UPDATE mangos_string SET content_loc4='当前没有G M登录在这台服务器上.' WHERE entry=17;
UPDATE mangos_string SET content_loc4='当处于飞行中时，无法这样做.' WHERE entry=18;
UPDATE mangos_string SET content_loc4='目标在飞行中，你无法这样做.' WHERE entry=20;
UPDATE mangos_string SET content_loc4='在战场里无法这样做.' WHERE entry=19;
UPDATE mangos_string SET content_loc4='%s 正在飞行中, 命令无效.' WHERE entry=21;
UPDATE mangos_string SET content_loc4='你没有在骑乘状态, 因此你不能卸下骑乘.' WHERE entry=22;
UPDATE mangos_string SET content_loc4='在战斗中无法这样做.' WHERE entry=23;
UPDATE mangos_string SET content_loc4='您最近已经使用过它.' WHERE entry=24;
UPDATE mangos_string SET content_loc4='您的密码不能设置超过16个字符长度(客户极限), 密码没被改变' WHERE entry=25;
UPDATE mangos_string SET content_loc4='密码已经修改.' WHERE entry=26;
UPDATE mangos_string SET content_loc4='新口令不匹配或旧密码是错误的.' WHERE entry=27;
UPDATE mangos_string SET content_loc4='你的账号现在被锁定.' WHERE entry=28;
UPDATE mangos_string SET content_loc4='你的账号已取消锁定.' WHERE entry=29;
UPDATE mangos_string SET content_loc4='排名 ' WHERE entry=30;
UPDATE mangos_string SET content_loc4=' [学会]' WHERE entry=31;
UPDATE mangos_string SET content_loc4=' [学习]' WHERE entry=32;
UPDATE mangos_string SET content_loc4=' [被动的]' WHERE entry=33;
UPDATE mangos_string SET content_loc4=' [天赋]' WHERE entry=34;
UPDATE mangos_string SET content_loc4=' [激活]' WHERE entry=35;
UPDATE mangos_string SET content_loc4=' [完成]' WHERE entry=36;
UPDATE mangos_string SET content_loc4=' (离线)' WHERE entry=37;
UPDATE mangos_string SET content_loc4='开' WHERE entry=38;
UPDATE mangos_string SET content_loc4='关' WHERE entry=39;
UPDATE mangos_string SET content_loc4='你是: %s' WHERE entry=40;
UPDATE mangos_string SET content_loc4='显示' WHERE entry=41;
UPDATE mangos_string SET content_loc4='隐藏' WHERE entry=42;
UPDATE mangos_string SET content_loc4='完成' WHERE entry=43;
UPDATE mangos_string SET content_loc4='你' WHERE entry=44;
UPDATE mangos_string SET content_loc4=' <未知> ' WHERE entry=45;
UPDATE mangos_string SET content_loc4='<错误>' WHERE entry=46;
UPDATE mangos_string SET content_loc4='<查无此人>' WHERE entry=47;
UPDATE mangos_string SET content_loc4='未知' WHERE entry=48;
UPDATE mangos_string SET content_loc4='你必须达到 %u 级后进入.' WHERE entry=49;
UPDATE mangos_string SET content_loc4='你必须达到 %u 级,并且拥有道具 %s 方可进入.' WHERE entry=50;
UPDATE mangos_string SET content_loc4='你好! 准备学习什么技能吗?' WHERE entry=51;
UPDATE mangos_string SET content_loc4='物品 %u 的数量错误 (%u)' WHERE entry=52;
UPDATE mangos_string SET content_loc4='邮件不能堆放更多的物品 %u' WHERE entry=53;
UPDATE mangos_string SET content_loc4='新密码不匹配' WHERE entry=54;
UPDATE mangos_string SET content_loc4='你是密码长度不能超过16个字符（客户端限制），密码没有改变!' WHERE entry=55;
UPDATE mangos_string SET content_loc4='当前信息的日期: %s' WHERE entry=56;
UPDATE mangos_string SET content_loc4='使用 World 数据库: %s' WHERE entry=57;
UPDATE mangos_string SET content_loc4='使用脚本库: %s' WHERE entry=58;
UPDATE mangos_string SET content_loc4='使用生物事件AI: %s' WHERE entry=59;
UPDATE mangos_string SET content_loc4='在线玩家数: %u (max: %u)' WHERE entry=60;
UPDATE mangos_string SET content_loc4='用户名：' WHERE entry=61;
UPDATE mangos_string SET content_loc4='密码：' WHERE entry=62;
UPDATE mangos_string SET content_loc4='接收悄悄话：' WHERE entry=63;
UPDATE mangos_string SET content_loc4='不接受悄悄话：' WHERE entry=64;
UPDATE mangos_string SET content_loc4='使用脚本库：<未知的脚本库>' WHERE entry=65;
UPDATE mangos_string SET content_loc4='使用脚本库：<没有脚本库加载>' WHERE entry=66;
UPDATE mangos_string SET content_loc4='全区广播:\n' WHERE entry=100;
UPDATE mangos_string SET content_loc4='地图: %u (%s) 地域: %u (%s) 地区: %u (%s) Phase: %u
X: %f Y: %f Z: %f Orientation: %f
grid[%u,%u]cell[%u,%u] InstanceID: %u
 ZoneX: %f ZoneY: %f
GroundZ: %f FloorZ: %f Have height data (Map: %u VMap: %u)' WHERE entry=101;
UPDATE mangos_string SET content_loc4='系统提示：%s 已被远距传送.' WHERE entry=102;
UPDATE mangos_string SET content_loc4='系统提示：你可以召唤一个玩家到你的副本，前提是必须在同一队伍，而且你是队长.' WHERE entry=103;
UPDATE mangos_string SET content_loc4='系统提示：你无法传送到玩家 %s 的副本，因为你们不在同一队伍.' WHERE entry=104;
UPDATE mangos_string SET content_loc4='系统提示：传送到不是同一队伍的玩家 %s 的副本需要开启ＧＭ模式.' WHERE entry=105;
UPDATE mangos_string SET content_loc4='系统提示：你无法传送到玩家  %s 从副本到副本.' WHERE entry=106;
UPDATE mangos_string SET content_loc4='系统提示：你不能召唤这个玩家 %s 从副本到副本.' WHERE entry=107;
UPDATE mangos_string SET content_loc4='系统提示：你正在召唤 %s%s.' WHERE entry=108;
UPDATE mangos_string SET content_loc4='系统提示：你正在被 %s 召唤中.' WHERE entry=109;
UPDATE mangos_string SET content_loc4='系统提示：你正在传送  %s%s to %s.' WHERE entry=110;
UPDATE mangos_string SET content_loc4='系统提示：你正在被 %s 传送.' WHERE entry=111;
UPDATE mangos_string SET content_loc4='系统提示：玩家 (%s) 不存在.' WHERE entry=112;
UPDATE mangos_string SET content_loc4='系统提示：出现在 %s 的地点.' WHERE entry=113;
UPDATE mangos_string SET content_loc4='系统提示：%s 出现在你的位置.' WHERE entry=114;
UPDATE mangos_string SET content_loc4='系统提示：无效参数.' WHERE entry=115;
UPDATE mangos_string SET content_loc4='系统提示：没有选定角色.' WHERE entry=116;
UPDATE mangos_string SET content_loc4='系统提示：%s 不在同一队伍里.' WHERE entry=117;
UPDATE mangos_string SET content_loc4='系统提示：你改变了 %s 的血量值 HP to %i/%i.' WHERE entry=118;
UPDATE mangos_string SET content_loc4='系统提示：%s 改变了你的血量值 HP 到 %i/%i.' WHERE entry=119;
UPDATE mangos_string SET content_loc4='系统提示：你改变了 %s 的魔法值 MANA 到 %i/%i.' WHERE entry=120;
UPDATE mangos_string SET content_loc4='系统提示：%s 改变了你的魔法值 MANA 到 %i/%i.' WHERE entry=121;
UPDATE mangos_string SET content_loc4='系统提示：你改变了 %s 的能量值 ENERGY 到 %i/%i.' WHERE entry=122;
UPDATE mangos_string SET content_loc4='系统提示：%s 改变了你的能量值 ENERGY 到 %i/%i.' WHERE entry=123;
UPDATE mangos_string SET content_loc4='系统提示：当前的能量: %u' WHERE entry=124;
UPDATE mangos_string SET content_loc4='系统提示：你改变了 %s 的怒气值 RAGE 到 %i/%i.' WHERE entry=125;
UPDATE mangos_string SET content_loc4='系统提示：%s 改变了你的怒气值 RAGE 到 %i/%i.' WHERE entry=126;
UPDATE mangos_string SET content_loc4='系统提示：你改变了 %s 的等级到 %i.' WHERE entry=127;
UPDATE mangos_string SET content_loc4='系统提示：GUID %i, faction is %i, flags is %i, npcflag is %i' WHERE entry=128;
UPDATE mangos_string SET content_loc4='系统提示：错误 faction: %u (在factiontemplate.dbc中没有发现).' WHERE entry=129;
UPDATE mangos_string SET content_loc4='系统提示：你改变了 GUID=%i ''s Faction to %i, flags to %i,' WHERE entry=130;
UPDATE mangos_string SET content_loc4='你改变了 the spellflatid=%i, val= %i, mark =%i ' WHERE entry=131;
UPDATE mangos_string SET content_loc4='系统提示：%s 改变了你的 spellflatid=%i, val= %i, mark =%i.' WHERE entry=132;
UPDATE mangos_string SET content_loc4='系统提示：%s 获得了所有的飞行点 (直到注销).' WHERE entry=133;
UPDATE mangos_string SET content_loc4='系统提示：%s 没有更多地可获得的飞行点(仅显示容易接近的).' WHERE entry=134;
UPDATE mangos_string SET content_loc4='系统提示：%s 给你进入所有飞行点 (直到注销).' WHERE entry=135;
UPDATE mangos_string SET content_loc4='系统提示：%s 已取消进出所有飞行点(仅显示仍然容易接近的).' WHERE entry=136;
UPDATE mangos_string SET content_loc4='系统提示：你设置了所有的速度到 %2.2f 从基础值 %s.' WHERE entry=137;
UPDATE mangos_string SET content_loc4='系统提示：%s 设置了你所有的速度到 %2.2f 从基础值.' WHERE entry=138;
UPDATE mangos_string SET content_loc4='系统提示：你设置了移动速度到 %2.2f 从基础值 %s.' WHERE entry=139;
UPDATE mangos_string SET content_loc4='系统提示：%s 设置了你的移动速度到 %2.2f 从基础值.' WHERE entry=140;
UPDATE mangos_string SET content_loc4='系统提示：你设置了游泳速度到 %2.2f 从基础值 %s.' WHERE entry=141;
UPDATE mangos_string SET content_loc4='系统提示：%s 设置了你的游泳速度到 %2.2f 从基础值.' WHERE entry=142;
UPDATE mangos_string SET content_loc4='系统提示：设置了后退速度到 %2.2f 从基础值 %s.' WHERE entry=143;
UPDATE mangos_string SET content_loc4='系统提示：%s 设置了你的后退速度到 %2.2f 从基础值.' WHERE entry=144;
UPDATE mangos_string SET content_loc4='系统提示：你设置了飞行速度到 %2.2f 从基础值 %s.' WHERE entry=145;
UPDATE mangos_string SET content_loc4='系统提示：%s 设置你的飞行速度到 %2.2f 从基础值.' WHERE entry=146;
UPDATE mangos_string SET content_loc4='系统提示：你设置了这个比例 %2.2f of %s.' WHERE entry=147;
UPDATE mangos_string SET content_loc4='系统提示：%s 设置你的比例为 %2.2f.' WHERE entry=148;
UPDATE mangos_string SET content_loc4='系统提示：没有此类骑术.' WHERE entry=149;
UPDATE mangos_string SET content_loc4='系统提示：你把一个骑术送给 %s.' WHERE entry=150;
UPDATE mangos_string SET content_loc4='系统提示：%s 送给你一个骑术.' WHERE entry=151;
UPDATE mangos_string SET content_loc4='用户1: %i, 增加: %i, DIF: %i' WHERE entry=152;
UPDATE mangos_string SET content_loc4='你拿走了所有的铜币从 %s.' WHERE entry=153;
UPDATE mangos_string SET content_loc4='%s 拿走了你所有的铜币.' WHERE entry=154;
UPDATE mangos_string SET content_loc4='你拿走了 %i 铜币从 %s.' WHERE entry=155;
UPDATE mangos_string SET content_loc4='%s 拿走了 %i 铜币从你这里.' WHERE entry=156;
UPDATE mangos_string SET content_loc4='你把 %i 铜币给了 %s.' WHERE entry=157;
UPDATE mangos_string SET content_loc4='%s 给你 %i  铜币.' WHERE entry=158;
UPDATE mangos_string SET content_loc4='你听到声音 %u.' WHERE entry=159;
UPDATE mangos_string SET content_loc4='用户2: %i, 增加: %i, 结果: %i' WHERE entry=160;
UPDATE mangos_string SET content_loc4='移除位 %i 在字段 %i.' WHERE entry=161;
UPDATE mangos_string SET content_loc4='设置位 %i 在字段 %i.' WHERE entry=162;
UPDATE mangos_string SET content_loc4='远距传送地点表是空的!' WHERE entry=163;
UPDATE mangos_string SET content_loc4='远距传送地点没被发现!' WHERE entry=164;
UPDATE mangos_string SET content_loc4='需要搜索参数.' WHERE entry=165;
UPDATE mangos_string SET content_loc4='没有远距传物地点匹配您的请求.' WHERE entry=166;
UPDATE mangos_string SET content_loc4='发现地点是: ' WHERE entry=168;
UPDATE mangos_string SET content_loc4='邮件寄给 %s' WHERE entry=169;
UPDATE mangos_string SET content_loc4='你试着听声音 %u 但是它并不存在.' WHERE entry=170;
UPDATE mangos_string SET content_loc4='你不能传送自己到自己!' WHERE entry=171;
UPDATE mangos_string SET content_loc4='服务器控制台命令.' WHERE entry=172;
UPDATE mangos_string SET content_loc4='当前符文: %u/%u/%u/%u/%u/%u' WHERE entry=173;
UPDATE mangos_string SET content_loc4='你将符文从 %s 改变为 %i/%i.' WHERE entry=174;
UPDATE mangos_string SET content_loc4='液体等级: %f, 地面: %f, 类型: %d, 状态: %d' WHERE entry=175;
UPDATE mangos_string SET content_loc4='没有选择.' WHERE entry=200;
UPDATE mangos_string SET content_loc4='对象 GUID is: 低部分 %u 高部分 %X' WHERE entry=201;
UPDATE mangos_string SET content_loc4='这个名字长度超过了 %i 字符.' WHERE entry=202;
UPDATE mangos_string SET content_loc4='错误,名字只能包含字符 A-Z 和 a-z.' WHERE entry=203;
UPDATE mangos_string SET content_loc4='次级名字太长超过了 %i 字符.' WHERE entry=204;
UPDATE mangos_string SET content_loc4='未能实施.' WHERE entry=205;
UPDATE mangos_string SET content_loc4='物品 ''%i'' ''%s'' 以加入到列表且最大数 ''%i'' 复生时间 ''%i''' WHERE entry=206;
UPDATE mangos_string SET content_loc4='物品 ''%i'' 在数据库里没有找到.' WHERE entry=207;
UPDATE mangos_string SET content_loc4='物品 ''%i'' ''%s'' 已经从商人列表中删除.' WHERE entry=208;
UPDATE mangos_string SET content_loc4='物品 ''%i'' 没有找到在商人的列表里.' WHERE entry=209;
UPDATE mangos_string SET content_loc4='物品 ''%i'' 已经在商人的列表里.' WHERE entry=210;
UPDATE mangos_string SET content_loc4='法术 %s 重置.' WHERE entry=211;
UPDATE mangos_string SET content_loc4='法术 %s 将在下次登陆时重置.' WHERE entry=212;
UPDATE mangos_string SET content_loc4='天赋 %s 重置.' WHERE entry=213;
UPDATE mangos_string SET content_loc4='天赋 %s 将在下次登陆时重置.' WHERE entry=214;
UPDATE mangos_string SET content_loc4='你的法术已经重置了.' WHERE entry=215;
UPDATE mangos_string SET content_loc4='你的天赋已经重置了.' WHERE entry=216;
UPDATE mangos_string SET content_loc4='未知的参数 ''%s'' 为 .resetall 命令. 键入完整的正确参数名字.' WHERE entry=217;
UPDATE mangos_string SET content_loc4='法术将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=218;
UPDATE mangos_string SET content_loc4='天赋将重置在所有玩家在重新登录后. 强烈推荐重新登录!' WHERE entry=219;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 没有飞行点发现.' WHERE entry=220;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 飞行终点没有找到.' WHERE entry=221;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 没有飞行点发现 - 请用  ''wpguid''. 现在设法发现它由它的位置...' WHERE entry=222;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 没有飞行点发现 - 这是一个MaNGOS db 问题 (single float).' WHERE entry=223;
UPDATE mangos_string SET content_loc4='选择的生物被忽略 - 提供的 GUID 已经被占用.' WHERE entry=224;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 没有找到.' WHERE entry=225;
UPDATE mangos_string SET content_loc4='您必须选择一个视觉飞行点.' WHERE entry=226;
UPDATE mangos_string SET content_loc4='没有找到视觉飞行点.' WHERE entry=227;
UPDATE mangos_string SET content_loc4='不能创建视觉飞行点的 生物ID: %d' WHERE entry=228;
UPDATE mangos_string SET content_loc4='所有视觉飞行点消除.' WHERE entry=229;
UPDATE mangos_string SET content_loc4='不能创建 飞行点-生物的 ID: %d' WHERE entry=230;
UPDATE mangos_string SET content_loc4='没有 GUID 被提供.' WHERE entry=231;
UPDATE mangos_string SET content_loc4='没有提供飞行点数值.' WHERE entry=232;
UPDATE mangos_string SET content_loc4='根据要求为 ''%s''.' WHERE entry=233;
UPDATE mangos_string SET content_loc4='飞行点 %i 添加到 GUID: %d' WHERE entry=234;
UPDATE mangos_string SET content_loc4='飞行点 %d 已添加.' WHERE entry=235;
UPDATE mangos_string SET content_loc4='飞行点已变动.' WHERE entry=236;
UPDATE mangos_string SET content_loc4='飞行点 %s 已修改.' WHERE entry=237;
UPDATE mangos_string SET content_loc4='飞行点出口成功.' WHERE entry=238;
UPDATE mangos_string SET content_loc4='没有飞行点被发现在数据库里.' WHERE entry=239;
UPDATE mangos_string SET content_loc4='文件已导入.' WHERE entry=240;
UPDATE mangos_string SET content_loc4='飞行点取消.' WHERE entry=241;
UPDATE mangos_string SET content_loc4='警告: 不能删除这个飞行点从世界里且 ID: %d' WHERE entry=242;
UPDATE mangos_string SET content_loc4='出现这种情况，是因为飞行点过于远离你.' WHERE entry=243;
UPDATE mangos_string SET content_loc4='这个飞行点已经从数据库删除, 但不是从世界这里.' WHERE entry=244;
UPDATE mangos_string SET content_loc4='他们将消失，当服务器重新启动之后.' WHERE entry=245;
UPDATE mangos_string SET content_loc4='飞行点 %d: 生物信息: %s, GUID: %d' WHERE entry=246;
UPDATE mangos_string SET content_loc4='等待时间: %d' WHERE entry=247;
UPDATE mangos_string SET content_loc4='方向 %d: %d' WHERE entry=248;
UPDATE mangos_string SET content_loc4='脚本ID: %u' WHERE entry=249;
UPDATE mangos_string SET content_loc4='ScriptID设置为不存在的id%u，将其添加到DBScriptsEngine并重新加载表。' WHERE entry=250;
UPDATE mangos_string SET content_loc4='文本%d (ID: %i): %s' WHERE entry=251;
UPDATE mangos_string SET content_loc4='AI脚本: %s' WHERE entry=252;
UPDATE mangos_string SET content_loc4='强制修改玩家名 %s, 将于下次登录时生效.' WHERE entry=253;
UPDATE mangos_string SET content_loc4='强制修改玩家名 %s (GUID #%u), 将于下次登录时生效.' WHERE entry=254;
UPDATE mangos_string SET content_loc4='飞行点-生物 (GUID: %u) 没有找到.' WHERE entry=255;
UPDATE mangos_string SET content_loc4='不能查找NPC...' WHERE entry=256;
UPDATE mangos_string SET content_loc4='生物运动方式设置为 ''%s'', 飞行点去除 (如果任何).' WHERE entry=257;
UPDATE mangos_string SET content_loc4='生物运动方式设置为 ''%s'', 飞行点没有去除.' WHERE entry=258;
UPDATE mangos_string SET content_loc4='错误值, 请用 on 或 off ' WHERE entry=259;
UPDATE mangos_string SET content_loc4='设置已保存.' WHERE entry=260;
UPDATE mangos_string SET content_loc4='设置已保存, 你可能需要重新清理你的客户缓存.' WHERE entry=261;
UPDATE mangos_string SET content_loc4='区域触发(传送门) ID %u 没有发现! ' WHERE entry=262;
UPDATE mangos_string SET content_loc4='目标地图或坐标无效 (X: %f Y: %f MapId: %u)' WHERE entry=263;
UPDATE mangos_string SET content_loc4='区域传送门无效 (X: %f Y: %f AreaId: %u)' WHERE entry=264;
UPDATE mangos_string SET content_loc4='Zone %u (%s) is part of instanceable map %u (%s)' WHERE entry=265;
UPDATE mangos_string SET content_loc4='没任何发现!' WHERE entry=266;
UPDATE mangos_string SET content_loc4='对象没有找到!' WHERE entry=267;
UPDATE mangos_string SET content_loc4='生物没有找到!' WHERE entry=268;
UPDATE mangos_string SET content_loc4='警告: 怪物发现超过一次 - 你将使用的是第一个在DB数据里的记录.' WHERE entry=269;
UPDATE mangos_string SET content_loc4='生物已经移除.' WHERE entry=270;
UPDATE mangos_string SET content_loc4='生物已经移动. ' WHERE entry=271;
UPDATE mangos_string SET content_loc4='生物 (GUID:%u) 必须与玩家在同样的地图!' WHERE entry=272;
UPDATE mangos_string SET content_loc4='游戏对象 (GUID: %u) 没有找到.' WHERE entry=273;
UPDATE mangos_string SET content_loc4='游戏对象 (GUID: %u) 有一个参考于没有找到生物 %u 是名单, 不能被删除.' WHERE entry=274;
UPDATE mangos_string SET content_loc4='游戏对象 (GUID: %u) 去除.' WHERE entry=275;
UPDATE mangos_string SET content_loc4='游戏对象 (GUID: %u) 转动.' WHERE entry=276;
UPDATE mangos_string SET content_loc4='游戏对象 (GUID: %u) 移动.' WHERE entry=277;
UPDATE mangos_string SET content_loc4='你必须选择一个商人' WHERE entry=278;
UPDATE mangos_string SET content_loc4='你必须使用物品的id' WHERE entry=279;
UPDATE mangos_string SET content_loc4='商人设置了太多的物品 (最多128)' WHERE entry=280;
UPDATE mangos_string SET content_loc4='你不能踢出你自己，使用退出代替.' WHERE entry=281;
UPDATE mangos_string SET content_loc4='角色 %s 已踢出.' WHERE entry=282;
UPDATE mangos_string SET content_loc4='接受悄悄话: %s' WHERE entry=284;
UPDATE mangos_string SET content_loc4='接受悄悄话: ON' WHERE entry=285;
UPDATE mangos_string SET content_loc4='接受悄悄话: OFF' WHERE entry=286;
UPDATE mangos_string SET content_loc4='生物 (GUID: %u) 没有找到.' WHERE entry=287;
UPDATE mangos_string SET content_loc4='票数量: %i 出示新的票: %s ' WHERE entry=288;
UPDATE mangos_string SET content_loc4='新票开始于 %s' WHERE entry=289;
UPDATE mangos_string SET content_loc4='Ticket of %s (Last updated: %s):%s' WHERE entry=290;
UPDATE mangos_string SET content_loc4='新票显示: ON' WHERE entry=291;
UPDATE mangos_string SET content_loc4='新票显示: OFF' WHERE entry=292;
UPDATE mangos_string SET content_loc4='票 %i 不存在.' WHERE entry=293;
UPDATE mangos_string SET content_loc4='所有票已删除.' WHERE entry=294;
UPDATE mangos_string SET content_loc4='角色 %s 票已删除.' WHERE entry=295;
UPDATE mangos_string SET content_loc4='票已删除.' WHERE entry=296;
UPDATE mangos_string SET content_loc4='复生间隔改变为: %i' WHERE entry=297;
UPDATE mangos_string SET content_loc4='复生时间改变为: %i' WHERE entry=298;
UPDATE mangos_string SET content_loc4='%s的%s字段被设置为%u' WHERE entry=299;
UPDATE mangos_string SET content_loc4='你的闲谈将被关闭 %u 分钟.' WHERE entry=300;
UPDATE mangos_string SET content_loc4='你被关闭了 %s 的聊天时间 %u 分钟.' WHERE entry=301;
UPDATE mangos_string SET content_loc4='玩的聊天已经可以使用.' WHERE entry=302;
UPDATE mangos_string SET content_loc4='你的聊天已经可以使用.' WHERE entry=303;
UPDATE mangos_string SET content_loc4='你已经可以使用 %s 的聊天了.' WHERE entry=304;
UPDATE mangos_string SET content_loc4='势力 %s (%u) 声望 %s 设置为 %5d!' WHERE entry=305;
UPDATE mangos_string SET content_loc4='%s 的竞技场点数设置为 %u!' WHERE entry=306;
UPDATE mangos_string SET content_loc4='没有阵营被发现' WHERE entry=307;
UPDATE mangos_string SET content_loc4='阵营 %i 未知!' WHERE entry=308;
UPDATE mangos_string SET content_loc4='无效的参数 %s' WHERE entry=309;
UPDATE mangos_string SET content_loc4='delta 必须在 0 到 %d 之间(包括)' WHERE entry=310;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H势力:%d|h[%s]|h|r' WHERE entry=311;
UPDATE mangos_string SET content_loc4=' [显示状态]' WHERE entry=312;
UPDATE mangos_string SET content_loc4=' [交战状态]' WHERE entry=313;
UPDATE mangos_string SET content_loc4=' [和平状态]' WHERE entry=314;
UPDATE mangos_string SET content_loc4=' [潜行状态]' WHERE entry=315;
UPDATE mangos_string SET content_loc4=' [强制隐形]' WHERE entry=316;
UPDATE mangos_string SET content_loc4=' [无效状态]' WHERE entry=317;
UPDATE mangos_string SET content_loc4='仇恨' WHERE entry=318;
UPDATE mangos_string SET content_loc4='敌对' WHERE entry=319;
UPDATE mangos_string SET content_loc4='不友好' WHERE entry=320;
UPDATE mangos_string SET content_loc4='中立' WHERE entry=321;
UPDATE mangos_string SET content_loc4='友好的' WHERE entry=322;
UPDATE mangos_string SET content_loc4='荣誉的' WHERE entry=323;
UPDATE mangos_string SET content_loc4='尊敬的' WHERE entry=324;
UPDATE mangos_string SET content_loc4='高贵的' WHERE entry=325;
UPDATE mangos_string SET content_loc4='势力 %s (%u) 没有声望.' WHERE entry=326;
UPDATE mangos_string SET content_loc4=' [没有声望]' WHERE entry=327;
UPDATE mangos_string SET content_loc4='角色在账户 %s (Id: %u)' WHERE entry=328;
UPDATE mangos_string SET content_loc4='  %s (GUID %u)' WHERE entry=329;
UPDATE mangos_string SET content_loc4='真没找到玩家!' WHERE entry=330;
UPDATE mangos_string SET content_loc4='扩展项成本 %u 不存在' WHERE entry=331;
UPDATE mangos_string SET content_loc4='GM 模式开启' WHERE entry=332;
UPDATE mangos_string SET content_loc4='GM 模式关闭' WHERE entry=333;
UPDATE mangos_string SET content_loc4='GM 交谈标记已打开' WHERE entry=334;
UPDATE mangos_string SET content_loc4='GM 交谈标记已关闭' WHERE entry=335;
UPDATE mangos_string SET content_loc4='你修复了 %s 的所有物品.' WHERE entry=336;
UPDATE mangos_string SET content_loc4='你的所有物品被 %s 修理了.' WHERE entry=337;
UPDATE mangos_string SET content_loc4='你设置了水上行走模式  %s 给 %s.' WHERE entry=338;
UPDATE mangos_string SET content_loc4='你的水上行走模式已由%s转换为%s。' WHERE entry=339;
UPDATE mangos_string SET content_loc4='%s 现在跟随您.' WHERE entry=340;
UPDATE mangos_string SET content_loc4='%s 没有跟随你.' WHERE entry=341;
UPDATE mangos_string SET content_loc4='%s 现在没有跟随你.' WHERE entry=342;
UPDATE mangos_string SET content_loc4='生物 (Entry: %u) 无法被驯服.' WHERE entry=343;
UPDATE mangos_string SET content_loc4='你已经有宠物了.' WHERE entry=344;
UPDATE mangos_string SET content_loc4='用户 %s 被要求下次登录时强制修改.' WHERE entry=345;
UPDATE mangos_string SET content_loc4='用户 %s (GUID #%u) 被要求下次登录时强制修改.' WHERE entry=346;
UPDATE mangos_string SET content_loc4='飞行点 %u 没有找到!' WHERE entry=347;
UPDATE mangos_string SET content_loc4='游戏对象 (Entry: %u) 含有无效数据，无法生成' WHERE entry=348;

UPDATE mangos_string SET content_loc4='区域触发器%u没有目标坐标' WHERE entry=357;
UPDATE mangos_string SET content_loc4='找不到区域触发器！' WHERE entry=358;

UPDATE mangos_string SET content_loc4='%s|cffffffff|Hareatrigger_target:%u|h[Trigger target %u]|h|r 地图 %u X:%f Y:%f Z:%f%s' WHERE entry=359;
UPDATE mangos_string SET content_loc4='%s[触发器 目标 %u] Map %u X:%f Y:%f Z:%f' WHERE entry=360;
UPDATE mangos_string SET content_loc4='|cffffffff|H区域触发器:%u|h[触发器 %u]|h|r 地图 %u X:%f Y:%f Z:%f%s%s%s' WHERE entry=361;
UPDATE mangos_string SET content_loc4='[触发器 %u] Map %u X:%f Y:%f Z:%f%s%s' WHERE entry=362;
UPDATE mangos_string SET content_loc4='(距离 %f)' WHERE entry=363;
UPDATE mangos_string SET content_loc4=' [酒馆]' WHERE entry=364;
UPDATE mangos_string SET content_loc4='[探索]' WHERE entry=365;
UPDATE mangos_string SET content_loc4='探索任务：' WHERE entry=366;
UPDATE mangos_string SET content_loc4='需要级别%u' WHERE entry=367;
UPDATE mangos_string SET content_loc4='需要物品：' WHERE entry=368;
UPDATE mangos_string SET content_loc4='需要任务:' WHERE entry=369;
UPDATE mangos_string SET content_loc4='响应: %s ' WHERE entry=373;
UPDATE mangos_string SET content_loc4='投票总数: %i' WHERE entry=374;
UPDATE mangos_string SET content_loc4='玩家 %s 没有投票.' WHERE entry=375;
UPDATE mangos_string SET content_loc4='%u - |cffffffff|H资源:%u|h[%s]|h|r 自动刷新: %u 最大限度: %u 生物: %u 游戏对象: %u 资源 %u' WHERE entry=376;
UPDATE mangos_string SET content_loc4='地图 %s 没有找到资源(Id:%u)' WHERE entry=377;
UPDATE mangos_string SET content_loc4='不能在非可实例化映射%s（Id:%u）上使用此命令。请改用.lookup pool命令。' WHERE entry=378;
UPDATE mangos_string SET content_loc4='在非可实例映射%s（Id:%u）中，不能使用没有参数的此命令。' WHERE entry=379;

UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|H生物:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r 概率:%f %s' WHERE entry=380;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d 概率:%f %s' WHERE entry=381;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|H生物:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s' WHERE entry=382;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s' WHERE entry=383;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|H游戏对象:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r 概率:%f %s' WHERE entry=384;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d 概率:%f %s' WHERE entry=385;
UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|H游戏对象:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r %s' WHERE entry=386;
UPDATE mangos_string SET content_loc4='%d%s - [%s] X:%f Y:%f Z:%f MapId:%d %s' WHERE entry=387;

UPDATE mangos_string SET content_loc4='有明确危险的生物:' WHERE entry=388;
UPDATE mangos_string SET content_loc4='机会均等的生物：' WHERE entry=389;
UPDATE mangos_string SET content_loc4='具有明确机会的游戏对象：' WHERE entry=390;
UPDATE mangos_string SET content_loc4='机会均等的游戏对象：' WHERE entry=391;

UPDATE mangos_string SET content_loc4='资源 %u - 母资源: %u |cffffffff|H资源:%u|h[%s]|h|r 自动刷新: %u 最大限制: %u' WHERE entry=392;
UPDATE mangos_string SET content_loc4='资源 %u - 母资源: %u [%s] 自动刷新: %u 最大限制: %u' WHERE entry=393;
UPDATE mangos_string SET content_loc4='资源 %u - 母资源: 没有自动刷新: %u 最大限制: %u' WHERE entry=394;

UPDATE mangos_string SET content_loc4='找不到资源' WHERE entry=395;
UPDATE mangos_string SET content_loc4='%u - [%s] 自动刷新: %u 最大限制: %u 生物: %u 游戏对象: %u 资源 %u' WHERE entry=396;

UPDATE mangos_string SET content_loc4='具有明确机会的资源：' WHERE entry=397;
UPDATE mangos_string SET content_loc4='具有同等机会的资源' WHERE entry=398;

UPDATE mangos_string SET content_loc4='%u - |cffffffff|H资源:%u|h[%s]|h|r 自动刷新: %u 最大限制: %u 生物: %u 游戏对象: %u 资源 %u 概率: %f %s' WHERE entry=399;

UPDATE mangos_string SET content_loc4='|cffff0000[系统信息]:|r脚本重新加载' WHERE entry=400;
UPDATE mangos_string SET content_loc4='你改变了 %s 的安全等级为 %i.' WHERE entry=401;
UPDATE mangos_string SET content_loc4='%s 改变了你的安全等级为 %i.' WHERE entry=402;
UPDATE mangos_string SET content_loc4='你这是低的防护等级.' WHERE entry=403;
UPDATE mangos_string SET content_loc4='生物移动点取消.' WHERE entry=404;
UPDATE mangos_string SET content_loc4='生物移动点生效.' WHERE entry=405;
UPDATE mangos_string SET content_loc4='这个区域的天气不能被更改.' WHERE entry=406;
UPDATE mangos_string SET content_loc4='本服务器天气系统取消.' WHERE entry=407;
UPDATE mangos_string SET content_loc4='%s 被禁止的为 %s. 操作: %s.' WHERE entry=408;
UPDATE mangos_string SET content_loc4='%s 被永久禁止的为 %s.' WHERE entry=409;
UPDATE mangos_string SET content_loc4='%s %s 没有发现.' WHERE entry=410;
UPDATE mangos_string SET content_loc4='%s 已解除禁止.' WHERE entry=411;
UPDATE mangos_string SET content_loc4='出现错误取消禁令 %s.' WHERE entry=412;
UPDATE mangos_string SET content_loc4='没有这个帐户.' WHERE entry=413;
UPDATE mangos_string SET content_loc4='没有这个角色.' WHERE entry=414;
UPDATE mangos_string SET content_loc4='没有这样的IP 在禁止名单.' WHERE entry=415;
UPDATE mangos_string SET content_loc4='账号 %s 从来没被禁止.' WHERE entry=416;
UPDATE mangos_string SET content_loc4='历史禁止帐户 %s:' WHERE entry=417;
UPDATE mangos_string SET content_loc4='禁止日期: %s 禁止时间: %s 激活间隔: %s  原因: %s 操作者: %s' WHERE entry=418;
UPDATE mangos_string SET content_loc4='信息。' WHERE entry=419;
UPDATE mangos_string SET content_loc4='从未' WHERE entry=420;
UPDATE mangos_string SET content_loc4='是' WHERE entry=421;
UPDATE mangos_string SET content_loc4='不' WHERE entry=422;
UPDATE mangos_string SET content_loc4='IP地址: %s 禁止日期: %s 解除禁止日期: %s 剩余: %s R' WHERE entry=423;
UPDATE mangos_string SET content_loc4='没有匹配的IP禁止地址.' WHERE entry=424;
UPDATE mangos_string SET content_loc4='没有匹配的帐户.' WHERE entry=425;
UPDATE mangos_string SET content_loc4='没有禁用的账号相匹配.' WHERE entry=426;
UPDATE mangos_string SET content_loc4='下面的IP地址符合您的匹配模式:' WHERE entry=427;
UPDATE mangos_string SET content_loc4='以下帐户匹配您的查询:' WHERE entry=428;
UPDATE mangos_string SET content_loc4='你学会了许多法术或技能.' WHERE entry=429;
UPDATE mangos_string SET content_loc4='你已经学会了所有的会职业法术.' WHERE entry=430;
UPDATE mangos_string SET content_loc4='你已经学会了所有的本职业天赋.' WHERE entry=431;
UPDATE mangos_string SET content_loc4='你已经学会了所有的语言.' WHERE entry=432;
UPDATE mangos_string SET content_loc4='你学会了所有手工艺技能和食谱.' WHERE entry=433;
UPDATE mangos_string SET content_loc4='不能查找 ''%s''' WHERE entry=434;
UPDATE mangos_string SET content_loc4='无效的物品 id: %u' WHERE entry=435;
UPDATE mangos_string SET content_loc4='没有找到物品!' WHERE entry=436;
UPDATE mangos_string SET content_loc4='无效的游戏物品对象 id: %u' WHERE entry=437;
UPDATE mangos_string SET content_loc4='找到物品 %u: %u ( 库存 %u 邮件 %u 拍卖 %u )' WHERE entry=438;
UPDATE mangos_string SET content_loc4='找到物品对象 %u: %u' WHERE entry=439;
UPDATE mangos_string SET content_loc4='无效的生物 id: %u' WHERE entry=440;
UPDATE mangos_string SET content_loc4='找到生物 %u: %u' WHERE entry=441;
UPDATE mangos_string SET content_loc4='没有地区被发现!' WHERE entry=442;
UPDATE mangos_string SET content_loc4='没有找到物品集!' WHERE entry=443;
UPDATE mangos_string SET content_loc4='没有找到此技能!' WHERE entry=444;
UPDATE mangos_string SET content_loc4='没有找到此法术!' WHERE entry=445;
UPDATE mangos_string SET content_loc4='没有找到此任务!' WHERE entry=446;
UPDATE mangos_string SET content_loc4='没有找到此生物!' WHERE entry=447;
UPDATE mangos_string SET content_loc4='没有找到此游戏物品对象!' WHERE entry=448;
UPDATE mangos_string SET content_loc4='墓地 #%u 不存在.' WHERE entry=449;
UPDATE mangos_string SET content_loc4='墓地 #%u 已经连接到区域 #%u (当前).' WHERE entry=450;
UPDATE mangos_string SET content_loc4='墓地 #%u 连接到区域 #%u (当前).' WHERE entry=451;
UPDATE mangos_string SET content_loc4='墓地 #%u 不能连接到子区域或不存在的区域 #%u (内部错误).' WHERE entry=452;
UPDATE mangos_string SET content_loc4='没有阵营在墓地且 id= #%u , 请修复你的DB数据库' WHERE entry=454;
UPDATE mangos_string SET content_loc4='错误的队伍, 请修复你的数据库' WHERE entry=455;
UPDATE mangos_string SET content_loc4='任何' WHERE entry=456;
UPDATE mangos_string SET content_loc4='联盟' WHERE entry=457;
UPDATE mangos_string SET content_loc4='部落' WHERE entry=458;
UPDATE mangos_string SET content_loc4='墓地ID #%u (阵营faction: %s) 是最近的距此区域zoneID #%u.' WHERE entry=459;
UPDATE mangos_string SET content_loc4='区域Zone #%u 没有一个连接的墓地.' WHERE entry=460;
UPDATE mangos_string SET content_loc4='区域Zone #%u 没有一个连接的墓地为阵营faction: %s.' WHERE entry=461;
UPDATE mangos_string SET content_loc4='远距传物地点已经存在!' WHERE entry=462;
UPDATE mangos_string SET content_loc4='远距传送地点增加.' WHERE entry=463;
UPDATE mangos_string SET content_loc4='远距传送地点没增加: 数据库错误.' WHERE entry=464;
UPDATE mangos_string SET content_loc4='远距传送地点被删除.' WHERE entry=465;
UPDATE mangos_string SET content_loc4='没有找到飞行点!' WHERE entry=466;
UPDATE mangos_string SET content_loc4='目标单位(unit)有 %d 光环auras:' WHERE entry=467;
UPDATE mangos_string SET content_loc4='id: %d 有效: %d 类型: %d 持续时间: %d 最大持续时间: %d 名字: %s%s%s 施法者: %s' WHERE entry=468;
UPDATE mangos_string SET content_loc4='目标单位有%d个 %d 光环类型:' WHERE entry=469;
UPDATE mangos_string SET content_loc4='id: %d 有效: %d 数量: %d' WHERE entry=470;
UPDATE mangos_string SET content_loc4='任务 %u 没有找到.' WHERE entry=471;
UPDATE mangos_string SET content_loc4='任务 %u 由物品触发. 为正确工作, 请, 添加物品到库里并且开始这个任务的正常方式: .additem %u' WHERE entry=472;
UPDATE mangos_string SET content_loc4='任务清除.' WHERE entry=473;
UPDATE mangos_string SET content_loc4=' [奖赏]' WHERE entry=474;
UPDATE mangos_string SET content_loc4=' [完成]' WHERE entry=475;
UPDATE mangos_string SET content_loc4=' [忙碌]' WHERE entry=476;
UPDATE mangos_string SET content_loc4='%s 的飞行模式为 %s' WHERE entry=477;
UPDATE mangos_string SET content_loc4='操作代码Opcode %u 发送到(sent to) %s' WHERE entry=478;
UPDATE mangos_string SET content_loc4='角色加载成功!' WHERE entry=479;
UPDATE mangos_string SET content_loc4='加载角色失败!' WHERE entry=480;
UPDATE mangos_string SET content_loc4='卸载角色成功!' WHERE entry=481;
UPDATE mangos_string SET content_loc4='卸载角色失败!' WHERE entry=482;
UPDATE mangos_string SET content_loc4='魔法 %u 失效，并且不允许使用或学习!' WHERE entry=483;
UPDATE mangos_string SET content_loc4='技能值 %u (%s) 为角色 %s 设置到 %u 并且当前最大设置到 %u (没有固定(天赋)奖励).' WHERE entry=484;
UPDATE mangos_string SET content_loc4='角色 %s 必须拥有技能 %u (%s) 在使用这个命令之前.' WHERE entry=485;
UPDATE mangos_string SET content_loc4='错误的技能 id (%u)' WHERE entry=486;
UPDATE mangos_string SET content_loc4='你学会了ＧＭ默认的法术和技能.' WHERE entry=487;
UPDATE mangos_string SET content_loc4='你已经学了这个法术.' WHERE entry=488;
UPDATE mangos_string SET content_loc4='目标 (%s) 已经学习了那些法术.' WHERE entry=489;
UPDATE mangos_string SET content_loc4='%s 不懂那些法术.' WHERE entry=490;
UPDATE mangos_string SET content_loc4='您已经忘记了那个法术.' WHERE entry=491;
UPDATE mangos_string SET content_loc4='所有的法术冷却清除 for %s.' WHERE entry=492;
UPDATE mangos_string SET content_loc4='法术 %u 冷却清除 for %s.' WHERE entry=493;
UPDATE mangos_string SET content_loc4='命令: Additem, itemId = %i, amount = %i' WHERE entry=494;
UPDATE mangos_string SET content_loc4='命令: Additemset, itemsetId = %i' WHERE entry=495;
UPDATE mangos_string SET content_loc4='移除物品ID = %i, amount = %i from %s' WHERE entry=496;
UPDATE mangos_string SET content_loc4='不能创建物品  ''%i'' (数量amount: %i)' WHERE entry=497;
UPDATE mangos_string SET content_loc4='系统提示：你需要提供一个公会名字!' WHERE entry=498;
UPDATE mangos_string SET content_loc4='系统提示：玩家没有被找到!' WHERE entry=499;
UPDATE mangos_string SET content_loc4='系统提示：玩家已经有一个公会!' WHERE entry=500;
UPDATE mangos_string SET content_loc4='公会没被创建! (是否已经存在?)' WHERE entry=501;
UPDATE mangos_string SET content_loc4='没有物品从物品库 ''%u'' 里找到.' WHERE entry=502;
UPDATE mangos_string SET content_loc4='距离是: (3D) %f (2D) %f (Exact 3D) %f (Exact 2D) %f yards.' WHERE entry=503;
UPDATE mangos_string SET content_loc4='物品 ''%i'' ''%s''  背包 %i' WHERE entry=504;
UPDATE mangos_string SET content_loc4='物品 ''%i'' 不存在.' WHERE entry=505;
UPDATE mangos_string SET content_loc4='物品 ''%i'' ''%s'' 已加入背包 %i' WHERE entry=506;
UPDATE mangos_string SET content_loc4='物品保存失败!' WHERE entry=507;
UPDATE mangos_string SET content_loc4='%d - 所有者: %s (guid: %u 账户: %u ) %s' WHERE entry=508;
UPDATE mangos_string SET content_loc4='%d - 发送者: %s (guid: %u 账户: %u ) 接受者: %s (guid: %u 账户: %u ) %s' WHERE entry=509;
UPDATE mangos_string SET content_loc4='%d - 所有者: %s (guid: %u 账户: %u ) %s' WHERE entry=510;
UPDATE mangos_string SET content_loc4='错误的链接类型!' WHERE entry=511;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H物品:%d:0:0:0:0:0:0:0|h[%s]|h|r ' WHERE entry=512;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H任务:%d|h[%s]|h|r %s' WHERE entry=513;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H生物id:%d|h[%s]|h|r ' WHERE entry=514;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H生物:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=515;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|Hgameobject_entry:%d|h[%s]|h|r ' WHERE entry=516;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H游戏对象:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=517;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H物品集:%d|h[%s %s]|h|r ' WHERE entry=518;
UPDATE mangos_string SET content_loc4='|cffffffff|H急救:%s|h[%s]|h|r ' WHERE entry=519;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H法术:%d|h[%s]|h|r ' WHERE entry=520;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H技能:%d|h[%s %s]|h|r %s' WHERE entry=521;
UPDATE mangos_string SET content_loc4='游戏对象 (GUID: %u) 没有找到' WHERE entry=522;
UPDATE mangos_string SET content_loc4='>> 游戏对象 %s (GUID: %u) at %f %f %f. 方向 %f.' WHERE entry=523;
UPDATE mangos_string SET content_loc4='选择物品:
|cffffffff|H游戏对象:%d|h[%s]|h|r GUID: %u ID: %u
X: %f Y: %f Z: %f MapId: %u
方向: %f
相位掩码 %u' WHERE entry=524;
UPDATE mangos_string SET content_loc4='>> 添加游戏对象 ''%i'' (%s) (GUID: %i) 在 ''%f %f %f''.' WHERE entry=525;
UPDATE mangos_string SET content_loc4='%s (lowguid: %u) 活动发电机组:' WHERE entry=526;
UPDATE mangos_string SET content_loc4='   闲置' WHERE entry=527;
UPDATE mangos_string SET content_loc4='   随机' WHERE entry=528;
UPDATE mangos_string SET content_loc4='   路标' WHERE entry=529;
UPDATE mangos_string SET content_loc4='   动物出没' WHERE entry=530;
UPDATE mangos_string SET content_loc4='   混乱' WHERE entry=531;
UPDATE mangos_string SET content_loc4='   标记用户 %s (lowguid %u)' WHERE entry=532;
UPDATE mangos_string SET content_loc4='   标记生物 %s (lowguid %u)' WHERE entry=533;
UPDATE mangos_string SET content_loc4='   标记 <NULL>' WHERE entry=534;
UPDATE mangos_string SET content_loc4='   炉石移动到 (X:%f Y:%f Z:%f)' WHERE entry=535;
UPDATE mangos_string SET content_loc4='   玩家使用了炉石?!?' WHERE entry=536;
UPDATE mangos_string SET content_loc4='   出租航班' WHERE entry=537;
UPDATE mangos_string SET content_loc4='   未知的动作发生 (%u)' WHERE entry=538;
UPDATE mangos_string SET content_loc4='玩家选择了 NPC
GUID: %u.
Faction: %u.
npcFlags: %u.
Entry: %u.
DisplayID: %u (Native: %u).' WHERE entry=539;
UPDATE mangos_string SET content_loc4='等级: %u.' WHERE entry=540;
UPDATE mangos_string SET content_loc4='生命值 (base): %u. (max): %u. (current): %u.' WHERE entry=541;
UPDATE mangos_string SET content_loc4='Field Flags: %u.
Dynamic Flags: %u.
Faction Template: %u.' WHERE entry=542;
UPDATE mangos_string SET content_loc4='战利品: %u 偷窃: %u 剥皮: %u' WHERE entry=543;
UPDATE mangos_string SET content_loc4='位置: %f %f %f.' WHERE entry=544;
UPDATE mangos_string SET content_loc4='*** 是一个销售师!' WHERE entry=545;
UPDATE mangos_string SET content_loc4='*** 是一个训练师!' WHERE entry=546;
UPDATE mangos_string SET content_loc4='副本ID: %u' WHERE entry=547;
UPDATE mangos_string SET content_loc4='玩家%s %s (guid: %u) 帐号: %s (id: %u) G M等级: %u 最后IP: %s 最后登陆: %s Latency: %ums' WHERE entry=548;
UPDATE mangos_string SET content_loc4='已登录时间: %s 等级: %u 金钱: %ug%us%uc' WHERE entry=549;
UPDATE mangos_string SET content_loc4='封禁剩余时间: %s, 封禁者: %s, 原因: %s' WHERE entry=453;

UPDATE mangos_string SET content_loc4='命令.pinfo不支持离线玩家的“rep”选项。' WHERE entry=550;
UPDATE mangos_string SET content_loc4='%s 探索了所有地区.' WHERE entry=551;
UPDATE mangos_string SET content_loc4='%s 没有更多的探索区.' WHERE entry=552;
UPDATE mangos_string SET content_loc4='%s 你探索了所有地带.' WHERE entry=553;
UPDATE mangos_string SET content_loc4='%s 你掩藏了所有区域.' WHERE entry=554;
UPDATE mangos_string SET content_loc4='悬停启用' WHERE entry=555;
UPDATE mangos_string SET content_loc4='已禁用悬停' WHERE entry=556;
UPDATE mangos_string SET content_loc4='%s 将你级别提升为 (%i)' WHERE entry=557;
UPDATE mangos_string SET content_loc4='%s 将你级别降低为 (%i)' WHERE entry=558;
UPDATE mangos_string SET content_loc4='%s 重置你的关卡进度.' WHERE entry=559;
UPDATE mangos_string SET content_loc4='该地区已被定为探索.' WHERE entry=560;
UPDATE mangos_string SET content_loc4='区域被设置了依照没被探索.' WHERE entry=561;
UPDATE mangos_string SET content_loc4='GUID=%i ''s 更新索引: %i, value:  %i.' WHERE entry=562;
UPDATE mangos_string SET content_loc4='你改变了 GUID=%i ''s UpdateIndex: %i value to %i.' WHERE entry=563;
UPDATE mangos_string SET content_loc4='索引值 %u 对于 %u(count: %u) 来说太大了.' WHERE entry=564;
UPDATE mangos_string SET content_loc4='设置 %u uint32 Value:[OPCODE]:%u [VALUE]:%u' WHERE entry=565;
UPDATE mangos_string SET content_loc4='你设置 %u Field:%u to uint32 Value: %u' WHERE entry=566;
UPDATE mangos_string SET content_loc4='设置 %u float Value:[OPCODE]:%u [VALUE]:%f' WHERE entry=567;
UPDATE mangos_string SET content_loc4='设置 %u Field:%i to float Value: %f' WHERE entry=568;
UPDATE mangos_string SET content_loc4='Get %u uint32 Value:[OPCODE]:%u [VALUE]:%u' WHERE entry=569;
UPDATE mangos_string SET content_loc4='The uint32 value of %u in %u is: %u' WHERE entry=570;
UPDATE mangos_string SET content_loc4='Get %u float Value:[OPCODE]:%u [VALUE]:%f' WHERE entry=571;
UPDATE mangos_string SET content_loc4='The float of %u value in %u is: %f' WHERE entry=572;
UPDATE mangos_string SET content_loc4='.Set32Bit:[OPCODE]:%u [VALUE]:%u' WHERE entry=573;
UPDATE mangos_string SET content_loc4='You set Bit of Field:%u to Value: %u' WHERE entry=574;
UPDATE mangos_string SET content_loc4='.Mod32Value:[OPCODE]:%u [VALUE]:%i' WHERE entry=575;
UPDATE mangos_string SET content_loc4='你修改了字段值:%u to Value: %u' WHERE entry=576;
UPDATE mangos_string SET content_loc4='你现在处于隐身状态.' WHERE entry=577;
UPDATE mangos_string SET content_loc4='你现在处于可见状态.' WHERE entry=578;
UPDATE mangos_string SET content_loc4='选定的玩家或生物没有祭品.' WHERE entry=579;
UPDATE mangos_string SET content_loc4='玩家 %s 学会了所有的本种族本职业的魔法,包括任何奖励的技能.' WHERE entry=580;
UPDATE mangos_string SET content_loc4='在对象附近找到 (距离 %f): %u ' WHERE entry=581;
UPDATE mangos_string SET content_loc4='刷新时间: Full:%s 剩余:%s' WHERE entry=582;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H游戏事件:%d|h[%s]|h|r%s' WHERE entry=583;
UPDATE mangos_string SET content_loc4='没有事件被找到!' WHERE entry=584;
UPDATE mangos_string SET content_loc4='事件不存在!' WHERE entry=585;
UPDATE mangos_string SET content_loc4='事件 %u: %s%s
开始: %s 结束: %s 发生: %s 全程: %s
下一次状态改变: %s' WHERE entry=586;
UPDATE mangos_string SET content_loc4='事件 %u 已经开始!' WHERE entry=587;
UPDATE mangos_string SET content_loc4='事件 %u 没有开始!' WHERE entry=588;
UPDATE mangos_string SET content_loc4='   点移动到 (X:%f Y:%f Z:%f)' WHERE entry=589;
UPDATE mangos_string SET content_loc4='   恐惧移动' WHERE entry=590;
UPDATE mangos_string SET content_loc4='   分散注意力' WHERE entry=591;
UPDATE mangos_string SET content_loc4='你已经学会了所有的法术: %s' WHERE entry=592;
UPDATE mangos_string SET content_loc4='当前被禁止的帐户:' WHERE entry=593;
UPDATE mangos_string SET content_loc4='|    账户    |   禁止时间    |   解禁时间  |  封禁者    |   封禁原因  |' WHERE entry=594;
UPDATE mangos_string SET content_loc4='当前被禁止IPs:' WHERE entry=595;
UPDATE mangos_string SET content_loc4='|      IP       |   禁止时间    |   解禁时间  |  封禁者    |   封禁原因  |' WHERE entry=596;
UPDATE mangos_string SET content_loc4='当前游戏管理员:' WHERE entry=597;
UPDATE mangos_string SET content_loc4='|    账号    |  GM  |' WHERE entry=598;
UPDATE mangos_string SET content_loc4='没有游戏管理员.' WHERE entry=599;
UPDATE mangos_string SET content_loc4='联盟获得胜利!' WHERE entry=600;
UPDATE mangos_string SET content_loc4='部落获得胜利!' WHERE entry=601;
UPDATE mangos_string SET content_loc4='战场战歌峡谷争夺1分钟倒计时中...' WHERE entry=602;
UPDATE mangos_string SET content_loc4='战场战歌峡谷争夺，在30秒后开始。大家做好准备!' WHERE entry=603;
UPDATE mangos_string SET content_loc4='战场战歌峡谷争夺正式开始!' WHERE entry=604;
UPDATE mangos_string SET content_loc4='$n 夺取了部落旗子!' WHERE entry=605;
UPDATE mangos_string SET content_loc4='$n 夺取了联盟旗子!' WHERE entry=606;
UPDATE mangos_string SET content_loc4='部落旗子被 $n 降下!' WHERE entry=607;
UPDATE mangos_string SET content_loc4='联盟旗子被 $n 降下!' WHERE entry=608;
UPDATE mangos_string SET content_loc4='联盟旗子被 $n 返回了到它的基地!' WHERE entry=609;
UPDATE mangos_string SET content_loc4='部落旗子被 $n 返回了到它的基地!' WHERE entry=610;
UPDATE mangos_string SET content_loc4='部落旗子被 $n 拾起!' WHERE entry=611;
UPDATE mangos_string SET content_loc4='魔兽世界：联盟旗子被 $n 拾起!' WHERE entry=612;
UPDATE mangos_string SET content_loc4='旗子现在被安置在他们的基地.' WHERE entry=613;
UPDATE mangos_string SET content_loc4='联盟旗帜已经被重置' WHERE entry=614;
UPDATE mangos_string SET content_loc4='联盟旗帜已经被重置!' WHERE entry=615;
UPDATE mangos_string SET content_loc4='战场暴风之眼争夺1分钟倒计时中....' WHERE entry=636;
UPDATE mangos_string SET content_loc4='战场暴风之眼争夺，在30秒后开始。大家做好准备!.' WHERE entry=637;
UPDATE mangos_string SET content_loc4='战场暴风之眼争夺正式开始!!' WHERE entry=638;
UPDATE mangos_string SET content_loc4='联盟' WHERE entry=650;
UPDATE mangos_string SET content_loc4='部落' WHERE entry=651;
UPDATE mangos_string SET content_loc4='兽栏' WHERE entry=652;
UPDATE mangos_string SET content_loc4='铁匠铺' WHERE entry=653;
UPDATE mangos_string SET content_loc4='农场' WHERE entry=654;
UPDATE mangos_string SET content_loc4='伐木场' WHERE entry=655;
UPDATE mangos_string SET content_loc4='金矿' WHERE entry=656;
UPDATE mangos_string SET content_loc4='此 %s 采取了 %s' WHERE entry=657;
UPDATE mangos_string SET content_loc4='$n 保卫了  %s' WHERE entry=658;
UPDATE mangos_string SET content_loc4='$n 攻击了  %s' WHERE entry=659;
UPDATE mangos_string SET content_loc4='$n 主持这个 %s 吧! 如果听之任之, 这个 %s 将在1 分钟之内控制它!' WHERE entry=660;
UPDATE mangos_string SET content_loc4='战场阿拉西盆地争夺1分钟倒计时中...' WHERE entry=661;
UPDATE mangos_string SET content_loc4='战场阿拉西盆地争夺，在30秒后开始。大家做好准备!' WHERE entry=662;
UPDATE mangos_string SET content_loc4='战场阿拉西盆地争夺正式开始!' WHERE entry=663;
UPDATE mangos_string SET content_loc4='联盟已收集到$1776W资源, 并已接近胜利!' WHERE entry=664;
UPDATE mangos_string SET content_loc4='部落已收集到$1777W资源, 并已接近胜利!' WHERE entry=665;
UPDATE mangos_string SET content_loc4='你在最近的 %s 战斗之后,我们努力想为你颁发一个荣誉标志却没有成功,结束后你会发现这个荣誉标志的,但不是此刻,感谢你在 %s 的战斗.' WHERE entry=666;
UPDATE mangos_string SET content_loc4='联盟控制了法师塔!' WHERE entry=667;
UPDATE mangos_string SET content_loc4='部落控制了法师塔!' WHERE entry=668;
UPDATE mangos_string SET content_loc4='联盟控制了德雷尼废墟!' WHERE entry=669;
UPDATE mangos_string SET content_loc4='部落控制了德雷尼废墟!' WHERE entry=670;
UPDATE mangos_string SET content_loc4='联盟控制了血精灵塔!' WHERE entry=671;
UPDATE mangos_string SET content_loc4='部落控制了血精灵塔!' WHERE entry=672;
UPDATE mangos_string SET content_loc4='联盟已经控制了费雷弗废墟!' WHERE entry=673;
UPDATE mangos_string SET content_loc4='部落已经控制了费雷弗废墟!' WHERE entry=674;
UPDATE mangos_string SET content_loc4='联盟已经失去了对法师塔的控制!' WHERE entry=675;
UPDATE mangos_string SET content_loc4='部落已经失去了对法师塔的控制!' WHERE entry=676;
UPDATE mangos_string SET content_loc4='联盟已经失去了对德雷尼废墟的控制!' WHERE entry=677;
UPDATE mangos_string SET content_loc4='部落已经失去了对德雷尼废墟的控制!' WHERE entry=678;
UPDATE mangos_string SET content_loc4='联盟已经失去了对血精灵塔的控制!' WHERE entry=679;
UPDATE mangos_string SET content_loc4='部落已经失去了对血精灵塔的控制!' WHERE entry=680;
UPDATE mangos_string SET content_loc4='联盟已经失去了对费雷弗废墟的控制!' WHERE entry=681;
UPDATE mangos_string SET content_loc4='部落已经失去了对费雷弗废墟的控制!' WHERE entry=682;
UPDATE mangos_string SET content_loc4='$N 夺走了旗子!' WHERE entry=683;
UPDATE mangos_string SET content_loc4='联盟已经占领了旗帜!' WHERE entry=684;
UPDATE mangos_string SET content_loc4='部落已经占领了旗帜!' WHERE entry=685;
UPDATE mangos_string SET content_loc4='旗子已经被降下!' WHERE entry=686;
UPDATE mangos_string SET content_loc4='旗帜已经被重置' WHERE entry=687;
UPDATE mangos_string SET content_loc4='你必须达到等级  %u 才能进入竞技场.' WHERE entry=700;
UPDATE mangos_string SET content_loc4='一分钟后竞技场争斗开始!' WHERE entry=701;
UPDATE mangos_string SET content_loc4='三十秒后竞技场争斗开始!' WHERE entry=702;
UPDATE mangos_string SET content_loc4='十五秒后竞技场争斗开始!' WHERE entry=703;
UPDATE mangos_string SET content_loc4='竞技场争斗开始了!' WHERE entry=704;
UPDATE mangos_string SET content_loc4='你必须等待 %s 才能继续喊话.' WHERE entry=705;
UPDATE mangos_string SET content_loc4='这些道具在装备/存放中出现一个问题.' WHERE entry=706;
UPDATE mangos_string SET content_loc4='%s 免打扰状态下无法收到悄悄话: %s' WHERE entry=707;
UPDATE mangos_string SET content_loc4='%s 不在机器旁: %s' WHERE entry=708;
UPDATE mangos_string SET content_loc4='请勿打扰' WHERE entry=709;
UPDATE mangos_string SET content_loc4='不在机器旁' WHERE entry=710;
UPDATE mangos_string SET content_loc4='队列状态 %s (Lvl: %u to %u)
排队联盟: %u (需要至少 %u)
排队部落: %u (需要至少 %u)' WHERE entry=711;
UPDATE mangos_string SET content_loc4='|cffff0000[战场公告]:|r %s -- [%u-%u] 联盟: 目前%u人 (需: %u人), 部落: 目前%u人 (需: %u人)|r' WHERE entry=712;
UPDATE mangos_string SET content_loc4='你的等级必须达到 %u 才能加入一个竞技场队伍!' WHERE entry=713;
UPDATE mangos_string SET content_loc4='不能达到进入战场的要求.' WHERE entry=715;
UPDATE mangos_string SET content_loc4='|cffff0000[战场队列播报者]:|r %s -- [%u-%u] 开始!|r' WHERE entry=717;
UPDATE mangos_string SET content_loc4='|cffff0000[竞技场队列播音者]:|r %s -- 加入 : %ux%u : %u|r' WHERE entry=718;
UPDATE mangos_string SET content_loc4='|cffff0000[竞技场队列播音者]:|r %s -- 离开 : %ux%u : %u|r' WHERE entry=719;
UPDATE mangos_string SET content_loc4='你的队伍对于这个战场来说太大了。请重新组织加入.' WHERE entry=720;
UPDATE mangos_string SET content_loc4='你的队伍对这个竞技场来说太大了。请重新组织加入.' WHERE entry=721;
UPDATE mangos_string SET content_loc4='您的队伍中有不在您的竞技场团队中的成员。请重新组织加入.' WHERE entry=722;
UPDATE mangos_string SET content_loc4='你的队伍没有足够的队员参加这场比赛.' WHERE entry=723;
UPDATE mangos_string SET content_loc4='黄队获胜!' WHERE entry=724;
UPDATE mangos_string SET content_loc4='绿队获胜!' WHERE entry=725;
UPDATE mangos_string SET content_loc4='没有足够的玩家，战场将很快结束。除非有更多的玩家加入.' WHERE entry=726;
UPDATE mangos_string SET content_loc4='您的队伍有一个成员离开。加入前请移除.' WHERE entry=727;
UPDATE mangos_string SET content_loc4='你的团队有来自对方阵营的玩家。你不能作为一个团体加入战场.' WHERE entry=728;
UPDATE mangos_string SET content_loc4='你的团队有来自不同战场的玩家。不能组队加入.' WHERE entry=729;
UPDATE mangos_string SET content_loc4='你的队伍里已经有人在此战场排队了，必须先离开才能加入.' WHERE entry=730;
UPDATE mangos_string SET content_loc4='有人是逃兵，不能团队加入.' WHERE entry=731;
UPDATE mangos_string SET content_loc4='已经有人在三个战场排队了，不能团队加入.' WHERE entry=732;
UPDATE mangos_string SET content_loc4='你不能传送到战场或竞技场地图.' WHERE entry=733;
UPDATE mangos_string SET content_loc4='你不能召唤玩家到战场或竞技场地图.' WHERE entry=734;
UPDATE mangos_string SET content_loc4='你必须在GM模式下才能传送到战场上的玩家.' WHERE entry=735;
UPDATE mangos_string SET content_loc4='你不能从另一个战场传送到一个战场。请先离开现在的战场.' WHERE entry=736;
UPDATE mangos_string SET content_loc4='竞技场设置为1v1进行调试。所以，不要作为一个团队加入.' WHERE entry=737;
UPDATE mangos_string SET content_loc4='竞技场设置为正常玩家数.' WHERE entry=738;
UPDATE mangos_string SET content_loc4='单人战场开启.战场设置（1V0）.' WHERE entry=739;
UPDATE mangos_string SET content_loc4='战场模式已更改为：正常状态.' WHERE entry=740;
UPDATE mangos_string SET content_loc4='根据团队评分刷新竞技场积分，这可能需要几分钟时间。请等待...' WHERE entry=741;
UPDATE mangos_string SET content_loc4='向玩家分配竞技场点数...' WHERE entry=742;
UPDATE mangos_string SET content_loc4='在线玩家竞技场积分设置完毕.' WHERE entry=743;
UPDATE mangos_string SET content_loc4='修改已加载竞技场团队的已玩次数、竞技场点数等，向在线玩家发送更新的统计信息...' WHERE entry=744;
UPDATE mangos_string SET content_loc4='修改完成.' WHERE entry=745;
UPDATE mangos_string SET content_loc4='完成竞技场点数更新.' WHERE entry=746;
UPDATE mangos_string SET content_loc4='linkGUID: %u, Entry: %u (%s)' WHERE entry=750;
UPDATE mangos_string SET content_loc4='没有足够的玩家。游戏将在%u秒内结束.' WHERE entry=751;
UPDATE mangos_string SET content_loc4='只有联盟才能使用这个传送门.' WHERE entry=752;
UPDATE mangos_string SET content_loc4='只有部落才能使用这个传送门.' WHERE entry=753;
UPDATE mangos_string SET content_loc4='%s 被 %s 摧毁!.' WHERE entry=759;
UPDATE mangos_string SET content_loc4='%s被%s拿走了！' WHERE entry=760;
UPDATE mangos_string SET content_loc4='%s被%s拿走了！' WHERE entry=761;
UPDATE mangos_string SET content_loc4='%s被%s拿走了！' WHERE entry=762;
UPDATE mangos_string SET content_loc4='%s被%s拿走了！' WHERE entry=763;
UPDATE mangos_string SET content_loc4='%s受到攻击！如果不管，则%s将占领它！' WHERE entry=764;
UPDATE mangos_string SET content_loc4='%s拿走了%s！它的补给现在将用于增援！' WHERE entry=765;

UPDATE mangos_string SET content_loc4='深铁矿洞' WHERE entry=766;
UPDATE mangos_string SET content_loc4='冷齿矿洞' WHERE entry=767;
UPDATE mangos_string SET content_loc4='雷矛急救站' WHERE entry=768;
UPDATE mangos_string SET content_loc4='丹巴达尔南部碉堡' WHERE entry=769;
UPDATE mangos_string SET content_loc4='丹巴达尔北部碉堡' WHERE entry=770;
UPDATE mangos_string SET content_loc4='雷矛墓地' WHERE entry=771;
UPDATE mangos_string SET content_loc4='冰翼碉堡' WHERE entry=772;
UPDATE mangos_string SET content_loc4='石炉墓地' WHERE entry=773;
UPDATE mangos_string SET content_loc4='石炉碉堡' WHERE entry=774;
UPDATE mangos_string SET content_loc4='雪落墓地' WHERE entry=775;
UPDATE mangos_string SET content_loc4='冰雪哨塔' WHERE entry=776;
UPDATE mangos_string SET content_loc4='冰雪墓地' WHERE entry=777;
UPDATE mangos_string SET content_loc4='哨塔高地' WHERE entry=778;
UPDATE mangos_string SET content_loc4='霜狼墓地' WHERE entry=779;
UPDATE mangos_string SET content_loc4='东部霜狼哨塔' WHERE entry=780;
UPDATE mangos_string SET content_loc4='西部霜狼哨塔' WHERE entry=781;
UPDATE mangos_string SET content_loc4='霜狼救援所' WHERE entry=782;

UPDATE mangos_string SET content_loc4='奥特拉克山谷的战斗一分钟后开始。' WHERE entry=784;
UPDATE mangos_string SET content_loc4='奥特拉克山谷的战斗30秒后开始。准备好了！' WHERE entry=785;
UPDATE mangos_string SET content_loc4='奥特拉克山谷的战斗已经开始了！' WHERE entry=786;
UPDATE mangos_string SET content_loc4='联盟的援军快用完了！' WHERE entry=787;
UPDATE mangos_string SET content_loc4='部落的援军快用完了！' WHERE entry=788;
UPDATE mangos_string SET content_loc4='霜狼将军死了！' WHERE entry=789;
UPDATE mangos_string SET content_loc4='雷矛将军死了！' WHERE entry=790;


update mangos_string set content_loc4='你的金币不足' where entry=801;
update mangos_string set content_loc4='你的包满了' where entry=802;
update mangos_string set content_loc4='你的队友包满了' where entry=803;
update mangos_string set content_loc4='您没有执行该功能的权限' where entry=804;
update mangos_string set content_loc4='未知的语言' where entry=805;
update mangos_string set content_loc4='你未学习这一种语言' where entry=806;
update mangos_string set content_loc4='请提供角色名字' where entry=807;
update mangos_string set content_loc4='玩家 %s 未发现或离线' where entry=808;
update mangos_string set content_loc4='账户的角色 %s 未发现' where entry=809;

update mangos_string set content_loc4='公会会长' where entry=811;
update mangos_string set content_loc4='公会官员' where entry=812;
update mangos_string set content_loc4='资深会员' where entry=813;
update mangos_string set content_loc4='公会成员' where entry=814;
update mangos_string set content_loc4='新入会员' where entry=815;

update mangos_string set content_loc4='正在退出后台程序...' where entry=1000;
update mangos_string set content_loc4='帐号被删除：%s' where entry=1001;
update mangos_string set content_loc4='帐号%s没有删除（可能sql档案格式已更新）' where entry=1002;
update mangos_string set content_loc4='帐号%s不删除（未知错误）' where entry=1003;
update mangos_string set content_loc4='帐号创建：%s' where entry=1004;
update mangos_string set content_loc4='帐号名长度无法超过16个字符（客户端限制） ，没有创建帐号！' where entry=1005;
update mangos_string set content_loc4='帐号与此名称已经存在！' where entry=1006;
update mangos_string set content_loc4='没有创建帐号%s的（可能是sql档案格式更新）' where entry=1007;
update mangos_string set content_loc4='没有创建帐号%s的（未知错误）' where entry=1008;
update mangos_string set content_loc4='玩家的%s（ GUID： %u）帐号的%s（ ID ：%su）删除。' where entry=1009;
update mangos_string set content_loc4='- ================================================= ================= - ' where entry=1012;
update mangos_string set content_loc4='| ID         |    账户    |       角色      |       IP        | GM | 插件 |' where entry=1010;
update mangos_string set content_loc4='没有在线玩家。' where entry=1014;



UPDATE mangos_string SET content_loc4='使用的不是完全类型的quit命令，需要完全键入它（quit），或者在RA命令行中没有使用的命令。' WHERE entry=1015;
UPDATE mangos_string SET content_loc4='| 工会       | 名字                 | 账户                      | 删除时间         |' WHERE entry=1016;
UPDATE mangos_string SET content_loc4='| %10u | %20s | %15s (%10u) | %19s |' WHERE entry=1017;
UPDATE mangos_string SET content_loc4='==========================================================================================' WHERE entry=1018;
UPDATE mangos_string SET content_loc4='没有找到角色.' WHERE entry=1019;

UPDATE mangos_string SET content_loc4='还原以下角色：' WHERE entry=1020;
UPDATE mangos_string SET content_loc4='删除下列角色：' WHERE entry=1021;
UPDATE mangos_string SET content_loc4='错误：如果只选择了一个角色，则只能指定新名称！' WHERE entry=1022;
UPDATE mangos_string SET content_loc4='角色 %s (GUID: %u 账户 %u) 不能保存: 账户不存在!' WHERE entry=1023;
UPDATE mangos_string SET content_loc4='角色 %s (GUID: %u 账户 %u) 不能保存: 账户角色列表满了!' WHERE entry=1024;
UPDATE mangos_string SET content_loc4='角色 %s (GUID: %u 账户 %u) 不能保存：该名字已被使用！' WHERE entry=1025;
UPDATE mangos_string SET content_loc4='GUID: %u 名字: %s 账号: %s (%u) 时间: %s' WHERE entry=1026;

UPDATE mangos_string SET content_loc4='日志筛选器状态：' WHERE entry=1027;
UPDATE mangos_string SET content_loc4='所有日志筛选器设置为%s' WHERE entry=1028;
UPDATE mangos_string SET content_loc4='命令只能从RA控制台调用。' WHERE entry=1029;

update mangos_string set content_loc4='帐户%s（Id:%u）现在最多允许%u个插件。' where entry=1100;
update mangos_string set content_loc4='今日信息变更为：%s' where entry=1101;
update mangos_string set content_loc4='信息发送到%s ： %s' where entry=1102;
update mangos_string set content_loc4='%d - %s %s' where entry=1103;
update mangos_string set content_loc4='%d - %s' where entry=1104;
update mangos_string set content_loc4='%d - %s' where entry=1105;
update mangos_string set content_loc4='%d - %s %s' where entry=1106;
update mangos_string set content_loc4='%d - %s' where entry=1107;
update mangos_string set content_loc4='%d - %s %s' where entry=1108;
update mangos_string set content_loc4='%d - %s %s %s %s' where entry=1109;
update mangos_string set content_loc4='%d - %s X:%f Y:%f Z:%f 地图Id:%d' where entry=1110;
update mangos_string set content_loc4='%d - %s X:%f Y:%f Z:%f 地图Id:%d' where entry=1111;
update mangos_string set content_loc4='无法打开档案：%s' where entry=1112;
update mangos_string set content_loc4='帐号的%s（ %u）有的角色超过最大限制（客户端限制）' where entry=1113;
update mangos_string set content_loc4='转储档案内有损坏的资料数据！' where entry=1114;
update mangos_string set content_loc4='无效人物的名称！' where entry=1115;
update mangos_string set content_loc4='无效的人物 GUID ！' where entry=1116;
update mangos_string set content_loc4='人物 GUID %u在使用！' where entry=1117;
update mangos_string set content_loc4='%d- 公会: %s(guid: %u) %s' where entry=1118;
update mangos_string set content_loc4='您必须使用男性或女性的性别。' where entry=1119;
update mangos_string set content_loc4='你改变性别由%s改成%s 。' where entry=1120;
update mangos_string set content_loc4='%s由%s改变你的性别。' where entry=1121;


UPDATE mangos_string SET content_loc4='（%u/%u+永久%u+临时%u）' WHERE entry=1122;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H飞行点:%u|h[%s %s]|h|r (地图:%u X:%f Y:%f Z:%f)' WHERE entry=1128;
UPDATE mangos_string SET content_loc4='%d - %s %s (Map:%u X:%f Y:%f Z:%f)' WHERE entry=1129;

UPDATE mangos_string SET content_loc4='事件已启动%u“%s”' WHERE entry=1130;
UPDATE mangos_string SET content_loc4='事件已停止%u“%s”' WHERE entry=1131;
UPDATE mangos_string SET content_loc4='跟随玩家%s（lowguid%u）' WHERE entry=1132;
UPDATE mangos_string SET content_loc4='跟随生物%s（lowguid%u）' WHERE entry=1133;
UPDATE mangos_string SET content_loc4='跟随 <NULL>' WHERE entry=1134;
UPDATE mangos_string SET content_loc4='列出已知天赋：' WHERE entry=1135;

UPDATE mangos_string SET content_loc4='（发现天赋%u使用的天赋点数%u）' WHERE entry=1136;

UPDATE mangos_string SET content_loc4='%d%s - |cffffffff|Hgameobject:%d|h[%s X:%f Y:%f Z:%f MapId:%d]|h|r ' WHERE entry=1137;
UPDATE mangos_string SET content_loc4='=================================================================================' WHERE entry=1138;
UPDATE mangos_string SET content_loc4='| 工会       | 名称                 | 种族            | 职业           | 等级 |' WHERE entry=1139;
UPDATE mangos_string SET content_loc4='| %10u | %20s | %15s | %15s | %5u |' WHERE entry=1140;
UPDATE mangos_string SET content_loc4='%u - |cffffffff|H玩家:%s|h[%s]|h|r %s %s %u' WHERE entry=1141;
UPDATE mangos_string SET content_loc4='%u - %s (在线:%s IP:%s GM:%u 插件:%u)' WHERE entry=1142;

UPDATE mangos_string SET content_loc4='事件%u (%s)已刷新' WHERE entry=1143;
UPDATE mangos_string SET content_loc4='事件%u (%s)已丢弃' WHERE entry=1144;

UPDATE mangos_string SET content_loc4='部分共享资源%u' WHERE entry=1145;
UPDATE mangos_string SET content_loc4='部分共享资源%u, 重要资源 %u' WHERE entry=1146;
UPDATE mangos_string SET content_loc4='重要资源 %u 被事件 %u (%s) 刷新' WHERE entry=1147;
UPDATE mangos_string SET content_loc4='重要资源 %u 被事件 %u (%s) 消失' WHERE entry=1148;

UPDATE mangos_string SET content_loc4='(资源 %u)' WHERE entry=1149;
UPDATE mangos_string SET content_loc4='(事件 %i)' WHERE entry=1150;
UPDATE mangos_string SET content_loc4='(资源 %u 事件 %i)' WHERE entry=1151;
UPDATE mangos_string SET content_loc4='[可用]' WHERE entry=1152;
UPDATE mangos_string SET content_loc4='获取%s 二进制字符串值：[字段]：%u[值]：%s' WHERE entry=1153;

UPDATE mangos_string SET content_loc4='%s具有二进制字符串值：[字段]：%u[值]：%s' WHERE entry=1154;
UPDATE mangos_string SET content_loc4='获取%s十六进制值：[字段]：%u[值]：%x' WHERE entry=1155;
UPDATE mangos_string SET content_loc4='%s具有十六进制值：[字段]：%u[值]：%x' WHERE entry=1156;
UPDATE mangos_string SET content_loc4='修改%s十六进制字段：%u%s%x=%x（十六进制）' WHERE entry=1157;
UPDATE mangos_string SET content_loc4='您修改了%s十六进制字段：%u%s%x=%x（十六进制）' WHERE entry=1158;
UPDATE mangos_string SET content_loc4='修改%s浮点字段%u以与%f进行求和%f' WHERE entry=1159;
UPDATE mangos_string SET content_loc4='您修改了%s浮点字段%u以与%f进行求和%f' WHERE entry=1160;
UPDATE mangos_string SET content_loc4='技能%u没有光环。' WHERE entry=1165;
UPDATE mangos_string SET content_loc4='找不到或无法访问脚本库。' WHERE entry=1166;
UPDATE mangos_string SET content_loc4='脚本库有错误的列表函数（过时？）。' WHERE entry=1167;
UPDATE mangos_string SET content_loc4='脚本库已重新加载。' WHERE entry=1168;
UPDATE mangos_string SET content_loc4='为不同的mangosd版本构建脚本库。' WHERE entry=1169;
update mangos_string set content_loc4='您尝试播放影片%u，但它不存在。' where entry=1200;
UPDATE mangos_string SET content_loc4='技能 %u %s = %f (*1.88 = %f) DB = %f AP = %f' WHERE entry=1202;
UPDATE mangos_string SET content_loc4='直接治疗' WHERE entry=1203;

UPDATE mangos_string SET content_loc4='直接伤害' WHERE entry=1204;
UPDATE mangos_string SET content_loc4='持续治疗' WHERE entry=1205;
UPDATE mangos_string SET content_loc4='持续治疗' WHERE entry=1206;

UPDATE mangos_string SET content_loc4='列兵' WHERE entry=1400;
UPDATE mangos_string SET content_loc4='下士' WHERE entry=1401;
UPDATE mangos_string SET content_loc4='中士' WHERE entry=1402;
UPDATE mangos_string SET content_loc4='军士长' WHERE entry=1403;
UPDATE mangos_string SET content_loc4='士官长' WHERE entry=1404;
UPDATE mangos_string SET content_loc4='骑士' WHERE entry=1405;
UPDATE mangos_string SET content_loc4='骑士中尉' WHERE entry=1406;
UPDATE mangos_string SET content_loc4='骑士队长' WHERE entry=1407;
UPDATE mangos_string SET content_loc4='护卫骑士' WHERE entry=1408;
UPDATE mangos_string SET content_loc4='少校' WHERE entry=1409;
UPDATE mangos_string SET content_loc4='司令' WHERE entry=1410;
UPDATE mangos_string SET content_loc4='统帅' WHERE entry=1411;
UPDATE mangos_string SET content_loc4='元帅' WHERE entry=1412;
UPDATE mangos_string SET content_loc4='大元帅' WHERE entry=1413;

UPDATE mangos_string SET content_loc4='侦察兵' WHERE entry=1414;
UPDATE mangos_string SET content_loc4='步兵' WHERE entry=1415;
UPDATE mangos_string SET content_loc4='中士' WHERE entry=1416;
UPDATE mangos_string SET content_loc4='高阶军士' WHERE entry=1417;
UPDATE mangos_string SET content_loc4='一等军士长' WHERE entry=1418;
UPDATE mangos_string SET content_loc4='石头守卫' WHERE entry=1419;
UPDATE mangos_string SET content_loc4='血卫士' WHERE entry=1420;
UPDATE mangos_string SET content_loc4='军团士兵' WHERE entry=1421;
UPDATE mangos_string SET content_loc4='百夫长' WHERE entry=1422;
UPDATE mangos_string SET content_loc4='勇士' WHERE entry=1423;
UPDATE mangos_string SET content_loc4='中将' WHERE entry=1424;
UPDATE mangos_string SET content_loc4='将军' WHERE entry=1425;
UPDATE mangos_string SET content_loc4='督军' WHERE entry=1426;
UPDATE mangos_string SET content_loc4='高阶督军' WHERE entry=1427;

UPDATE mangos_string SET content_loc4='游戏管理员' WHERE entry=1428;
UPDATE mangos_string SET content_loc4='没有等级' WHERE entry=1429;
UPDATE mangos_string SET content_loc4='无荣誉目标' WHERE entry=1430;
UPDATE mangos_string SET content_loc4='放逐' WHERE entry=1431;
UPDATE mangos_string SET content_loc4='逃亡者' WHERE entry=1432;
UPDATE mangos_string SET content_loc4='被遗忘者' WHERE entry=1433;
UPDATE mangos_string SET content_loc4='玩家: %s - %s (军衔 %u)' WHERE entry=1434;
UPDATE mangos_string SET content_loc4='今日: [荣誉击杀: |c0000ff00%u|r] [非荣誉击杀: |c00ff0000%u|r]' WHERE entry=1435;
UPDATE mangos_string SET content_loc4='昨日: [击杀: |c0000ff00%u|r] [荣誉: %u]' WHERE entry=1436;
UPDATE mangos_string SET content_loc4='本周: [击杀: |c0000ff00%u|r] [荣誉: %u]' WHERE entry=1437;
UPDATE mangos_string SET content_loc4='上周: [击杀: |c0000ff00%u|r] [荣誉: %u] [排名: %u]' WHERE entry=1438;
UPDATE mangos_string SET content_loc4='生涯: [军衔点: |c0000ff00%f|r] [荣誉击杀: |c0000ff00%u|r] [非荣誉击杀: |c00ff0000%u|r] [最高军衔 %u: %s]' WHERE entry=1439;
UPDATE mangos_string SET content_loc4='%u - [%s] 自动刷新: %u 最大限制: %u 生物: %u 游戏对象: %u 资源 %u 几率: %f %s' WHERE entry=1500;

UPDATE mangos_string SET content_loc4='%u - |cffffffff|H资源:%u|h[%s]|h|r 自动刷新: %u 最大限制: %u 生物: %u 游戏对象: %u 资源 %u %s' WHERE entry=1501;
UPDATE mangos_string SET content_loc4='%u - [%s] 自动刷新: %u 最大限制: %u 生物: %u 游戏对象: %u 资源 %u %s' WHERE entry=1502;
UPDATE mangos_string SET content_loc4='无法添加派生，因为在保留的guid范围内没有用于静态派生的可用guid。在使用命令之前，需要重新启动服务器。还要查看GuidReserveSize.*配置选项。' WHERE entry=1503;
UPDATE mangos_string SET content_loc4='入口为%u的Npc的AI信息' WHERE entry=1504;
UPDATE mangos_string SET content_loc4='AI名字: %s (%s) 脚本名: %s' WHERE entry=1505;
UPDATE mangos_string SET content_loc4='当前阶段=%u' WHERE entry=1506;
UPDATE mangos_string SET content_loc4='战斗移动为%s' WHERE entry=1507;
UPDATE mangos_string SET content_loc4='近战攻击是%s' WHERE entry=1508;
UPDATE mangos_string SET content_loc4='|cffffff00[|c1f40af20GM 公告者|r |cffff0000%s|cffffff00]:|r %s|r' WHERE entry=6615;
UPDATE mangos_string SET content_loc4='部落占领了北地哨塔！' WHERE entry=10033;
UPDATE mangos_string SET content_loc4='联盟占领了北地哨塔！' WHERE entry=10034;
UPDATE mangos_string SET content_loc4='部落占领了东墙哨塔！' WHERE entry=10035;
UPDATE mangos_string SET content_loc4='联盟占领了东墙哨塔！' WHERE entry=10036;
UPDATE mangos_string SET content_loc4='部落占领了皇冠哨塔！' WHERE entry=10037;
UPDATE mangos_string SET content_loc4='联盟占领了皇冠哨塔！' WHERE entry=10038;
UPDATE mangos_string SET content_loc4='部落占领了病木林哨塔！' WHERE entry=10039;
UPDATE mangos_string SET content_loc4='联盟占领了病木林哨塔！' WHERE entry=10040;

UPDATE mangos_string SET content_loc4='部落失去了北地哨塔！' WHERE entry=10041;
UPDATE mangos_string SET content_loc4='联盟失去了北地哨塔！' WHERE entry=10042;
UPDATE mangos_string SET content_loc4='部落失去了东墙哨塔！' WHERE entry=10043;
UPDATE mangos_string SET content_loc4='联盟失去了东墙哨塔！' WHERE entry=10044;
UPDATE mangos_string SET content_loc4='部落失去了皇冠哨塔！' WHERE entry=10045;
UPDATE mangos_string SET content_loc4='联盟失去了皇冠哨塔！' WHERE entry=10046;
UPDATE mangos_string SET content_loc4='部落失去了病木林哨塔！' WHERE entry=10047;
UPDATE mangos_string SET content_loc4='联盟失去了病木林哨塔！' WHERE entry=10048;

UPDATE mangos_string SET content_loc4='部落已经收集了200希利苏斯水晶！' WHERE entry=10049;
UPDATE mangos_string SET content_loc4='联盟已经收集了200希利苏斯水晶！' WHERE entry=10050;
UPDATE mangos_string SET content_loc4='带我去北地哨塔。' WHERE entry=10051;
UPDATE mangos_string SET content_loc4='带我去东墙哨塔。' WHERE entry=10052;
UPDATE mangos_string SET content_loc4='链接ID:%u' WHERE entry=11010;
UPDATE mangos_string SET content_loc4='加入英语社区频道（/Join WorldEN）与所有玩家讨论！' WHERE entry=11011;
UPDATE mangos_string SET content_loc4='命令“.go warsong”、“.go arathi”和“.go alterac”帮助您从任何地方加入战场！' WHERE entry=11012;
UPDATE mangos_string SET content_loc4='为了帮助服务器人口增加，启动一个招聘活动！提供NPC 60，从其他服务器输入字符，订阅我们的Facebook！' WHERE entry=11013;
UPDATE mangos_string SET content_loc4='服务器将于2008年19月关闭，以便进行国际发布，论坛中有更多信息' WHERE entry=11014;
UPDATE mangos_string SET content_loc4='我想浏览一下你的商品。' WHERE entry=2000;

UPDATE mangos_string SET content_loc4='nostarius是一个PVP&PVE服务器。无名氏，想让别人厌恶的玩家将受到惩罚' WHERE entry=11015;
UPDATE mangos_string SET content_loc4='提供赏金猎人系统，请联系游戏管理员以给出某人的底价，更多信息请参见论坛、活动部分' WHERE entry=11016;
UPDATE mangos_string SET content_loc4='训练我！' WHERE entry=2001;
UPDATE mangos_string SET content_loc4='%她企图在恐惧中逃跑！' WHERE entry=5030;
UPDATE mangos_string SET content_loc4='斯尼维尔来了！斯尼维尔说是我的冷杉！' WHERE entry=791;
UPDATE mangos_string SET content_loc4='现在是进攻的时候了！为了部落！' WHERE entry=792;
UPDATE mangos_string SET content_loc4='振作起来，联盟！把这些来自奥特兰克山谷的恶棍扔出去！' WHERE entry=793;
UPDATE mangos_string SET content_loc4='%u - |c00f00fff*|r|cffffffff|H玩家:%s|h[%s]|h|r %s %s %u' WHERE entry=11001;
UPDATE mangos_string SET content_loc4='%s %s%s %s (guid: %u) 账户: %s (id: %u%s) GM级别: %u 上次的IP: %s%s 上次登录: %s 延迟时间: %ums 客户端: %s 2FA: %s' WHERE entry=616;
UPDATE mangos_string SET content_loc4='|cff00ff00新投票来自于|r|cffff00ff %s.|r |cff00ff00类别:|r|cffff00ff %s.|r |cff00ff00投票入口:|r|cffff00ff %d.|r' WHERE entry=2052;
UPDATE mangos_string SET content_loc4='|cff00ff00角色|r|cffff00ff %s |r|cff00ff00放弃了他们的投票.投票入口:|r|cffff00ff %d.|r' WHERE entry=2002;
UPDATE mangos_string SET content_loc4='|cff00ff00关闭自|r:|cff00ccff %s|r ' WHERE entry=2003;
UPDATE mangos_string SET content_loc4='|cff00ff00删除自|r:|cff00ccff %s|r ' WHERE entry=2004;

update mangos_string set content_loc4='票据没找到.' where entry=2005;
update mangos_string set content_loc4='请先关闭票证，然后再永久删除它。' where entry=2006;
update mangos_string set content_loc4='票据 %d 已经被配置.' where entry=2007;
update mangos_string set content_loc4='%u 已被重新加载.' where entry=2008;
update mangos_string set content_loc4='显示未结票列表。' where entry=2009;
update mangos_string set content_loc4='显示在线的未结票据列表。.' where entry=2010;
update mangos_string set content_loc4='显示关闭的票据列表.' where entry=2011;
update mangos_string set content_loc4='指明了无效的名称。名称应该是一个在线的游戏中GM.' where entry=2012;
update mangos_string set content_loc4='已经被配置给自己。取消使用。取消配置改由 %d 配置.' where entry=2013;
update mangos_string set content_loc4='%d 未配置，你无法指定配置.' where entry=2014;
update mangos_string set content_loc4='与比自己更高的安全级别，你无法由工作人员配置.' where entry=2015;
update mangos_string set content_loc4='是 GM %d, 你无法结束 GM.' where entry=2016;

UPDATE mangos_string SET content_loc4='|cffaaffaa投票|r:|cffaaccff %d.|r ' WHERE entry=2017;
UPDATE mangos_string SET content_loc4='|cff00ff00创建者|r:|cff00ccff %s|r ' WHERE entry=2018;
UPDATE mangos_string SET content_loc4='|cff00ff00改变了|r:|cff00ccff %s ago|r ' WHERE entry=2019;

UPDATE mangos_string SET content_loc4='|cff00ff00分配给|r:|cff00ccff %s|r ' WHERE entry=2020;
UPDATE mangos_string SET content_loc4='|cff00ff00未分配给|r:|cff00ccff %s|r ' WHERE entry=2021;
UPDATE mangos_string SET content_loc4='|cff00ff00投票信息|r: [%s]|r' WHERE entry=2022;
UPDATE mangos_string SET content_loc4='|cff00ff00GM 评论|r: [%s]|r' WHERE entry=2023;
UPDATE mangos_string SET content_loc4='|cff00ccff%s|r |cff00ff00增加评论|r: [%s]|r' WHERE entry=2024;
UPDATE mangos_string SET content_loc4='|cff00ff00创建了|r:|cff00ccff %s 以前|r ' WHERE entry=2025;
UPDATE mangos_string SET content_loc4='有已经打开挂起的投票，请先关闭！' WHERE entry=2027;
UPDATE mangos_string SET content_loc4='已删除所有已关闭的投票，计数器重置为| cffff00ff 1 | r' WHERE entry=2028;
UPDATE mangos_string SET content_loc4='|CFF00FF00投票响应|r:[%s]| r' WHERE entry=2029;
UPDATE mangos_string SET content_loc4='|cff00ff00完成自|r:|cff00ccff %s|r ' WHERE entry=2030;
UPDATE mangos_string SET content_loc4='投票现在被禁用了' WHERE entry=2031;
UPDATE mangos_string SET content_loc4='现在可以投票了' WHERE entry=2040;
UPDATE mangos_string SET content_loc4='投票现在被禁用了' WHERE entry=2041;
UPDATE mangos_string SET content_loc4='投票%s响应已重置。' WHERE entry=2042;
UPDATE mangos_string SET content_loc4='此投票已存档（已完成或已关闭）。' WHERE entry=2043;
UPDATE mangos_string SET content_loc4='这张票已经分配给某人了。先取消分配。' WHERE entry=2044;
UPDATE mangos_string SET content_loc4='票据#%u已添加到升级列表。' WHERE entry=2045;
UPDATE mangos_string SET content_loc4='升级列表中的票证：' WHERE entry=2026;
UPDATE mangos_string SET content_loc4='%s: 等级 %u' WHERE entry=2046;
UPDATE mangos_string SET content_loc4='此票证已完成。请打开一个新的。' WHERE entry=2047;
UPDATE mangos_string SET content_loc4='您的票证已被编辑并有响应。' WHERE entry=2048;
UPDATE mangos_string SET content_loc4='GM票务柜台设置为票务#%u' WHERE entry=2051;
UPDATE mangos_string SET content_loc4='出现在%s的位置（脱机）。' WHERE entry=176;
UPDATE mangos_string SET content_loc4='%s复活（在线）' WHERE entry=5031;
UPDATE mangos_string SET content_loc4='%s复活（离线）' WHERE entry=5032;
UPDATE mangos_string SET content_loc4='|cff00ff00角色|r|cffff00ff %s |r|cff00ff00编辑了他们的票据. 票据入口:|r|cffff00ff %d.|r' WHERE entry=2053;
UPDATE mangos_string SET content_loc4='事件%u已禁用！' WHERE entry=1600;
UPDATE mangos_string SET content_loc4='事件%u已准备启用！' WHERE entry=1601;
UPDATE mangos_string SET content_loc4='事件%u已启用！' WHERE entry=1602;
UPDATE mangos_string SET content_loc4='事件%u已准备禁用！' WHERE entry=1603;
UPDATE mangos_string SET content_loc4='队伍类型: %s (ID: %s) 首领: %s 玩家总数: %d 玩家: %s' WHERE entry=640;
UPDATE mangos_string SET content_loc4='INVIS模式已启用' WHERE entry=345;
UPDATE mangos_string SET content_loc4='INVIS模式已关闭' WHERE entry=346;
UPDATE mangos_string SET content_loc4='上帝模式开启' WHERE entry=349;
UPDATE mangos_string SET content_loc4='上帝模式关闭' WHERE entry=350;

UPDATE mangos_string SET content_loc4='票证通知已启用。' WHERE entry=2049;
UPDATE mangos_string SET content_loc4='票证通知已禁止。' WHERE entry=2050;

UPDATE mangos_string SET content_loc4='你设置了爬墙模式给%s 为了%s' WHERE entry=351;

UPDATE mangos_string SET content_loc4='你修改了%s的力量到%i' WHERE entry=900;
UPDATE mangos_string SET content_loc4='%s修改了你的力量到%i' WHERE entry=901;
UPDATE mangos_string SET content_loc4='你修改了%s的敏捷到%i' WHERE entry=902;
UPDATE mangos_string SET content_loc4='%s修改了你的敏捷到%i' WHERE entry=903;
UPDATE mangos_string SET content_loc4='你修改了%s的耐力到%i' WHERE entry=904;
UPDATE mangos_string SET content_loc4='%s修改了你的耐力到%i' WHERE entry=905;
UPDATE mangos_string SET content_loc4='你修改了%s的智力到%i' WHERE entry=906;
UPDATE mangos_string SET content_loc4='%s修改了你的智力到%i' WHERE entry=907;
UPDATE mangos_string SET content_loc4='你修改了%s的精神到%i' WHERE entry=908;
UPDATE mangos_string SET content_loc4='%s修改了你的精神到%i' WHERE entry=909;
UPDATE mangos_string SET content_loc4='你修改了%s的护甲到%i' WHERE entry=910;
UPDATE mangos_string SET content_loc4='%s修改了你的护甲到%i' WHERE entry=911;
UPDATE mangos_string SET content_loc4='你修改了%s的神圣抵抗到%i' WHERE entry=912;
UPDATE mangos_string SET content_loc4='%s修改了你的神圣抵抗到%i' WHERE entry=913;
UPDATE mangos_string SET content_loc4='你修改了%s的火焰抗性到%i' WHERE entry=914;
UPDATE mangos_string SET content_loc4='%s修改了你的火焰抗性到%i' WHERE entry=915;
UPDATE mangos_string SET content_loc4='你修改了%s的自然抗性到%i' WHERE entry=916;
UPDATE mangos_string SET content_loc4='%s修改了你的自然抗性到%i' WHERE entry=917;
UPDATE mangos_string SET content_loc4='你修改了%s的冰霜抗性到%i' WHERE entry=918;
UPDATE mangos_string SET content_loc4='%s修改了你的冰霜抗性到%i' WHERE entry=919;
UPDATE mangos_string SET content_loc4='你修改了%s的暗影抗性到%i' WHERE entry=920;
UPDATE mangos_string SET content_loc4='%s修改了你的暗影抗性到%i' WHERE entry=921;
UPDATE mangos_string SET content_loc4='你修改了%s的奥术抗性到%i' WHERE entry=922;
UPDATE mangos_string SET content_loc4='%s修改了你的奥术抗性到%i' WHERE entry=923;
UPDATE mangos_string SET content_loc4='你修改了%s的近战攻击力到%i' WHERE entry=924;
UPDATE mangos_string SET content_loc4='%s修改了你的近战攻击力到%i' WHERE entry=925;
UPDATE mangos_string SET content_loc4='你修改了%s的远程攻击力到%i' WHERE entry=926;
UPDATE mangos_string SET content_loc4='%s修改了你的远程攻击力到%i' WHERE entry=927;
UPDATE mangos_string SET content_loc4='你修改了%s的法术强度到%i' WHERE entry=928;
UPDATE mangos_string SET content_loc4='%s修改了你的法术强度到%i' WHERE entry=929;
UPDATE mangos_string SET content_loc4='你修改了%s的近战暴击率到%i' WHERE entry=930;
UPDATE mangos_string SET content_loc4='%s修改了你的近战暴击率到%i' WHERE entry=931;
UPDATE mangos_string SET content_loc4='你修改了%s的远程暴击率到%i' WHERE entry=932;
UPDATE mangos_string SET content_loc4='%s修改了你的远程暴击率到%i' WHERE entry=933;
UPDATE mangos_string SET content_loc4='你修改了%s的法术暴击率到%i' WHERE entry=934;
UPDATE mangos_string SET content_loc4='%s修改了你的法术暴击率到%i' WHERE entry=935;

UPDATE mangos_string SET content_loc4='你修改了%s的主手攻速到%i' WHERE entry=936;
UPDATE mangos_string SET content_loc4='%s修改了你的主手攻速到%i' WHERE entry=937;
UPDATE mangos_string SET content_loc4='你修改了%s的副手攻速到%i' WHERE entry=938;
UPDATE mangos_string SET content_loc4='%s修改了你的副手攻速到%i' WHERE entry=939;
UPDATE mangos_string SET content_loc4='你修改了%s的远程武器攻速到%i' WHERE entry=940;
UPDATE mangos_string SET content_loc4='%s修改了你的远程武器攻速到%i' WHERE entry=941;
UPDATE mangos_string SET content_loc4='你修改了%s的施法速度到%i' WHERE entry=942;
UPDATE mangos_string SET content_loc4='%s修改了你的施法速度到%i' WHERE entry=943;
UPDATE mangos_string SET content_loc4='你修改了%s的格挡概率到%i' WHERE entry=944;
UPDATE mangos_string SET content_loc4='%s修改了你的格挡概率到%i' WHERE entry=945;
UPDATE mangos_string SET content_loc4='你修改了%s的闪避概率到%i' WHERE entry=946;
UPDATE mangos_string SET content_loc4='%s修改了你的闪避概率到%i' WHERE entry=947;
UPDATE mangos_string SET content_loc4='你修改了%s的招架概率到%i' WHERE entry=948;
UPDATE mangos_string SET content_loc4='%s修改了你的招架概率到%i' WHERE entry=949;

UPDATE mangos_string SET content_loc4='找不到公会。' WHERE entry=562;
UPDATE mangos_string SET content_loc4='试图邀请玩家加入公会时出错。' WHERE entry=563;

UPDATE mangos_string SET content_loc4='账户的锁定字段 %s (id %u) 修改为 %u.' WHERE entry=1170;
UPDATE mangos_string SET content_loc4='参数不正确。用法:
.account set locked <accountname> <value>
锁类型: 0 None, 1 IP, 2 PIN, 4 TOTP, 8 强制' WHERE entry=1171;
UPDATE mangos_string SET content_loc4='骑行类型无效。尝试下列操作之一：
%s' WHERE entry=1172;
UPDATE mangos_string SET content_loc4='该玩家没有%s骑术。' WHERE entry=1173;
UPDATE mangos_string SET content_loc4='尝试移除骑术时遇到错误。' WHERE entry=1174;
UPDATE mangos_string SET content_loc4='骑术从玩家%s中移除。' WHERE entry=1175;

UPDATE mangos_string SET content_loc4='此时不能使用untuck命令。' WHERE entry=67;
UPDATE mangos_string SET content_loc4='松开按钮激活。当buff过期时你将死去。不要进入战斗或施法，否则将被取消。请注意，此命令的任何使用都会被记录下来。' WHERE entry=68;
UPDATE mangos_string SET content_loc4='取消锁定功能已成功激活。你被传送到最近的墓地。请注意，此命令的任何使用都会被记录下来。' WHERE entry=69;
UPDATE mangos_string SET content_loc4='活动对象%d。可见性修饰符%0.2' WHERE entry=1030;
UPDATE mangos_string SET content_loc4='亲爱的玩家，
    请接受本函所附项目。它之前从你的角色中移除，因为它不应该在当前补丁中可用，但我们的技术人员已经得出结论，你现在可能有它回来！' WHERE entry=699;
UPDATE mangos_string SET content_loc4='设备ID:%u。' WHERE entry=1031;
UPDATE mangos_string SET content_loc4='驻留类型：%u' WHERE entry=1032;
UPDATE mangos_string SET content_loc4='护甲：%u' WHERE entry=1033;
UPDATE mangos_string SET content_loc4='AI名称: %s 脚本名: %s' WHERE entry=1034;
UPDATE mangos_string SET content_loc4='法力（基础）：%u（最大）：%u（当前）：%u。' WHERE entry=11017;
UPDATE mangos_string SET content_loc4='找不到声音。' WHERE entry=617;
UPDATE mangos_string SET content_loc4='%d - |cffffffff|H声音:%d|h[%s]|h|r ' WHERE entry=618;

UPDATE mangos_string SET content_loc4='模型 %d - |cffffffff|Hcreature_model_entry:%d|h[%s]|h|r ' WHERE entry=1176;
UPDATE mangos_string SET content_loc4='找不到生物模型！' WHERE entry=1177;
UPDATE mangos_string SET content_loc4='你设置了飞行速度到 %2.2f 从基础值 %s.' WHERE entry=145;
UPDATE mangos_string SET content_loc4='%s 设置你的飞行速度到 %2.2f 从基础值.' WHERE entry=146;
UPDATE mangos_string SET content_loc4='你发现了你阵营所有的飞行点。' WHERE entry=453;
UPDATE mangos_string SET content_loc4='团队首领试图重置您所在的副本。请出副本以允许实例副本。' WHERE entry=70;
UPDATE mangos_string SET content_loc4='动作类型%u' WHERE entry=1509;
UPDATE mangos_string SET content_loc4='不能将XP速率设置为低于%g！' WHERE entry=177;
UPDATE mangos_string SET content_loc4='不能将XP速率设置为高于%g！' WHERE entry=178;
UPDATE mangos_string SET content_loc4='您已将%s经验值更改为%g倍于正常经验值。' WHERE entry=179;
UPDATE mangos_string SET content_loc4='您的爬墙模式已由%s转到%s。' WHERE entry=352;
UPDATE mangos_string SET content_loc4='提示：要关闭服务器，请在控制台窗口中按CTRL+C。不要单击X按钮，否则会损坏数据库。' WHERE entry=7000;
UPDATE mangos_string SET content_loc4='提示：您可以通过在配置中设置WowPatch设置来模拟不同的内容修补程序。只需用记事本打开mangosd.conf并在那里更改它。值从0（1.2）到10（1.12）。' WHERE entry=7001;
UPDATE mangos_string SET content_loc4='提示：有一个支持不一致频道，您可以在那里获得任何与服务器相关的问题的帮助。检查自述文件中的链接。' WHERE entry=7002;
UPDATE mangos_string SET content_loc4='提示：如果你想编辑物品或生物统计信息，可以使用像HeidiSQL这样的sql客户端应用程序连接到数据库。' WHERE entry=7003;
UPDATE mangos_string SET content_loc4='提示：要在切换内容修补程序时查看项目的更改，您需要删除游戏的WDB缓存文件夹。' WHERE entry=7004;
UPDATE mangos_string SET content_loc4='提示：重新打包中包含一个脚本编辑器，您可以使用它编写生物脚本，而无需编写任何代码。' WHERE entry=7005;
UPDATE mangos_string SET content_loc4='提示：您可以在聊天室中键入.help以查看可用的gm命令列表。' WHERE entry=7006;

